---    
    - name: "Handling Create TR- Win@proach "
      block: 

        - set_fact:
            oview_lxca_record_id: ""
  

        - name: ESXi_host list
          shell: cat host_list_oview_lxca_enclosure.yml
          delegate_to: localhost
          register: hostlist_esxi       

        - name: save the esxi list to a Variable as a Fact
          set_fact:
            esxi_hostlist: "{{ hostlist_esxi.stdout[:-1] }}" 
          delegate_to: localhost 

        - meta: end_host
          when: esxi_hostlist == ""

        - name: TR creation for Oneview/xclarity deregister task for Enclosure
          create_tr_bird:
            username: "{{ btmp_user }}"
            password: "{{ btmp_password }}"
            bird: "{{ bird_api }}"
            template_name: "esxi oneview xclarity removal"
            cr_id: "{{ cr }}"
            ticket_title: "CSTY:DECO:DCAT: ESXI ENCLOSURE DECO : Oneview/xclarity deregister"
            ci: "{{ esxi_hostlist }}"
            winaproach_category: "{{ win_category }}" 
          register: ticket_id
          delegate_to: localhost
        
        - set_fact:
            oview_lxca_record_id: "{{ticket_id.id.ticketId}}"
    
        - copy:
            content: '{{ oview_lxca_record_id|to_json }}'
            dest: record_oview_lxca_enclosure.json
          delegate_to: localhost

    
      rescue:
        - debug:
            msg: "Failed to Create ESXi DECO - Oneview/xclarity deregister TR"

    - name: "Handling Create TR- Win@proach  -retry 1"
      block: 

        - name: Display the JSON file content
          shell: cat record_oview_lxca_enclosure.json
          delegate_to: localhost
          register: TR_result
    
        - name: save the Json data to a Variable as a Fact
          set_fact:
            oview_lxca_record_id: "{{ TR_result.stdout[1:-1] }}" 
          delegate_to: localhost

        - name: Sleep for 20 seconds and continue with play
          ansible.builtin.wait_for:
            timeout: 20
          delegate_to: localhost
          when: oview_lxca_record_id == ""

        - name: ESXi_host list
          shell: cat host_list_oview_lxca_enclosure.yml
          delegate_to: localhost
          register: hostlist_esxi              

        - name: save the esxi list to a Variable as a Fact
          set_fact:
            esxi_hostlist: "{{ hostlist_esxi.stdout[:-1] }}" 
          delegate_to: localhost 

        - meta: end_host
          when: esxi_hostlist == ""              

        - name: TR creation for Oneview/xclarity deregister task Enclosure
          create_tr_bird:
            username: "{{ btmp_user }}"
            password: "{{ btmp_password }}"
            bird: "{{ bird_api }}"
            template_name: "esxi oneview xclarity removal"
            cr_id: "{{ cr }}"
            ticket_title: "CSTY:DECO:DCAT: ESXI ENCLOSURE DECO : Oneview/xclarity deregister"
            ci: "{{ esxi_hostlist }}"
            winaproach_category: "{{ win_category }}" 
          register: ticket_id
          delegate_to: localhost
          when: oview_lxca_record_id == "" 
            

        - set_fact:
            oview_lxca_record_id: "{{ticket_id.id.ticketId}}"
          when: oview_lxca_record_id == ""   
         
        - copy:
            content: '{{ oview_lxca_record_id|to_json }}'
            dest: record_oview_lxca_enclosure.json
          delegate_to: localhost
          when: ticket_id is defined

    
      rescue:
        - debug:
            msg: "Failed to Create ESXi DECO - Oneview/xclarity deregister TR"

    - name: "Handling Create TR- Win@proach retry 2"
      block: 

        - name: Display the JSON file content
          shell: cat record_oview_lxca_enclosure.json
          delegate_to: localhost
          register: TR_result
    
        - name: save the Json data to a Variable as a Fact
          set_fact:
            oview_lxca_record_id: "{{ TR_result.stdout[1:-1] }}" 
          delegate_to: localhost

        - name: Sleep for 20 seconds and continue with play
          ansible.builtin.wait_for:
            timeout: 20
          delegate_to: localhost
          when: oview_lxca_record_id == ""                           

        - name: ESXi_host list
          shell: cat host_list_oview_lxca_enclosure.yml
          delegate_to: localhost
          register: hostlist_esxi              

        - name: save the esxi list to a Variable as a Fact
          set_fact:
            esxi_hostlist: "{{ hostlist_esxi.stdout[:-1] }}" 
          delegate_to: localhost 

        - meta: end_host
          when: esxi_hostlist == ""                 

        - name: TR creation for Oneview/xclarity deregister task 
          create_tr_bird:
            username: "{{ btmp_user }}"
            password: "{{ btmp_password }}"
            bird: "{{ bird_api }}"
            template_name: "esxi oneview xclarity removal"
            cr_id: "{{ cr }}"
            ticket_title: "CSTY:DECO:DCAT: ESXI ENCLOSURE DECO  : Oneview/xclarity deregister"
            ci: "{{ esxi_hostlist }}"
            winaproach_category: "{{ win_category }}" 
          register: ticket_id
          delegate_to: localhost
          when: oview_lxca_record_id == "" 
            

        - set_fact:
            oview_lxca_record_id: "{{ticket_id.id.ticketId}}"
          when: oview_lxca_record_id == "" 
    
        
        - copy:
            content: '{{ oview_lxca_record_id|to_json }}'
            dest: record_oview_lxca_enclosure.json
          delegate_to: localhost
          when: ticket_id is defined

    
      rescue:
        - debug:
            msg: "Failed to Create ESXi DECO - Oneview/xclarity deregister TR"            


    - name: "Handling Start Implementation- Win@proach "
      block:


        - name: Display the JSON file content
          shell: cat record_oview_lxca_enclosure.json
          delegate_to: localhost
          register: TR_result
    
        - name: save the Json data to a Variable as a Fact
          set_fact:
            oview_lxca_record_id: "{{ TR_result.stdout[1:-1] }}" 
          delegate_to: localhost         

        - meta: end_host
          when: oview_lxca_record_id == ""                            

        - name: Sleep for 62 seconds and continue with play
          ansible.builtin.wait_for:
            timeout: 62
          delegate_to: localhost           

        - name: Start Implementation
          winaproach:
            system: prod
            type: task_record
            operation: start_implementation
            username: "{{ winAproach_username }}"
            password: "{{ winAproach_password }}"
            fields:
              task_id: "{{ oview_lxca_record_id }}"
          register: start_implementation
          delegate_to: localhost
          
    
      rescue:
        - debug:
            msg: "Failed to Start Implementation on ESXi DECO - Oneview/xclarity enclosure deregister TR :'{{ oview_lxca_record_id }}'"
       
