---
    - name: "Check entry for DECO server from Azure table"
      block:

        - set_fact:
            host_list: host_list_oview_lxca_enclosure.yml


        - name: Display the JSON file content
          shell: cat private_endpoint_connection_string.yml
          delegate_to: localhost
          register: result_private_endpoint_connection_string
    
        - name: save the Json data to a Variable as a Fact
          set_fact:
            private_endpoint_connection_string: "{{ result_private_endpoint_connection_string.stdout }}"
          delegate_to: localhost      
                
        - name: "Check entry for DECO server for filter hostlist for Oneview/xclarity deregister"
          azure_update_ref_esxi:
            connection_string: "{{ private_endpoint_connection_string }}"
            hostname: "{{inventory_hostname}}"
          register: idem_status 
          delegate_to: localhost
        

        # - set_fact: 
        #     ipam_cleanup: '{{idem_status.module_update.ipam_cleanup}}'

        - set_fact: 
            oneview_xclarity_removal: '{{idem_status.module_update.oneview_xclarity_removal }}'                             
         

        - name: "ESXi list"
          shell: echo "{{ inventory_hostname }}," >> {{ host_list }}                   
          delegate_to: localhost
          # when: nvme_cleanup == "T" and ilo_reset == "F"                 
          when: oneview_xclarity_removal == "F"
            
      rescue:
        - debug:
            msg: "Failed to fetch hostlist for Oneview/LXCA Deregister For Enclosure"      

