---
    - name: "Check entry for DECO server"
      throttle: 1
      block:

        - name: Display the JSON file content
          shell: cat private_endpoint_connection_string.yml
          delegate_to: localhost
          run_once: true
          register: result_private_endpoint_connection_string
    
        - name: save the Json data to a Variable as a Fact
          set_fact:
            private_endpoint_connection_string: "{{ result_private_endpoint_connection_string.stdout }}"
          run_once: true
          delegate_to: localhost

        - name: "Check entry for DECO server"
          azure_update_ref_esxi.py:
            connection_string: "{{ private_endpoint_connection_string }}"
            hostname: "{{inventory_hostname}}"
          register: idem_status 
          delegate_to: localhost 


      rescue:
        - debug:
            var: idem_status