---   
    - name: "Handling Create TR- Win@proach for CMDB status check task "
      block:
        - set_fact:
            record_id_cmdb_stat: ""
            cmdb_stat_check_agp: "F"
            graceperiod_flag: True
            vm_poweroff_before_gp_check: "T"     

        - name: Display the JSON file content
          shell: cat record_healthcheck.json
          delegate_to: localhost
          register: TR_result_healthcheck  

        - name: save the Json data to a Variable as a Fact
          set_fact:
            record_id_healthcheck: "{{ TR_result_healthcheck.stdout[1:-1] }}"
          delegate_to: localhost

        - meta: end_host
          when: record_id_healthcheck != ""      

        - name: Display the JSON file content
          shell: cat record_healthcheck.json
          delegate_to: localhost
          register: TR_result_healthcheck  

        - name: save the Json data to a Variable as a Fact
          set_fact:
            record_id_healthcheck: "{{ TR_result_healthcheck.stdout[1:-1] }}"
          delegate_to: localhost

        - meta: end_host
          when: record_id_healthcheck != ""      

        - name: Display the JSON file content
          shell: cat idem_vm_poweroff_before_gp_check_pre.json
          delegate_to: localhost
          register: result_po_bf_cmdb

        - name: save the Json data to a Variable as a Fact
          set_fact:
            cmdb_po_flag_pre: "{{ result_po_bf_cmdb.stdout[1:-1] }}" 
          delegate_to: localhost

        - meta: end_host
          when: cmdb_po_flag_pre == "F"          
   

        - name: Display the JSON file content
          shell: cat idem_cmdb_stat_check_agp.json
          delegate_to: localhost
          register: result_app_cmdb_agp

        - name: save the Json data to a Variable as a Fact
          set_fact:
            cmdb_flag_agp: "{{ result_app_cmdb_agp.stdout[1:-1] }}" 
          delegate_to: localhost

        - meta: end_host
          when: cmdb_flag_agp == "T"
                
        - name: VM_host list
          shell: cat host_list_cmdb_agp.yml
          delegate_to: localhost
          register: hostlist_vm              

        - name: save the vm list to a Variable as a Fact
          set_fact:
            vm_hostlist: "{{ hostlist_vm.stdout[:-1] }}" 
          delegate_to: localhost 

        - meta: end_host
          when: vm_hostlist == ""

        - name: Display the JSON file content
          shell: cat winaproach_category.yml
          delegate_to: localhost
          register: result_winaproach_category

        - name: save the Json data to a Variable as a Fact
          set_fact:
            win_category: "{{ result_winaproach_category.stdout }}" 
          delegate_to: localhost 

        - name: Display the JSON file content
          shell: cat bird_api.yml
          delegate_to: localhost
          register: result_bird

        - name: save the Json data to a Variable as a Fact
          set_fact:
            bird_api: "{{ result_bird.stdout }}" 
          delegate_to: localhost                     

        - name: TR creation for CMDB status check task 
          create_tr_bird:
            username: "{{ btmp_user }}"
            password: "{{ btmp_password }}"
            bird: "{{ bird_api }}"
            template_name: "vm deco cmdb status check"
            cr_id: "{{ cr }}"
            ticket_title: "CSTY:DECO:DCAT: VM DECO : cmdb status check after grace period"
            ci: "{{ vm_hostlist }}"
            winaproach_category: "{{ win_category }}"
          register: ticket_id_cmdb_stat
          delegate_to: localhost
         

        - set_fact:
            record_id_cmdb_stat: "{{ticket_id_cmdb_stat.id.ticketId}}"

        - copy:
            content: '{{ record_id_cmdb_stat|to_json }}'
            dest: record_cmdb_stat.json
          delegate_to: localhost

      rescue:
        - debug:
            msg: "Failed to Create VM DECO - CMDB status check TR"

    - name: "Handling Create TR- Win@proach for CMDB status check task - Retry 1"
      block: 

        - name: Display the JSON file content
          shell: cat record_healthcheck.json
          delegate_to: localhost
          register: TR_result_healthcheck  

        - name: save the Json data to a Variable as a Fact
          set_fact:
            record_id_healthcheck: "{{ TR_result_healthcheck.stdout[1:-1] }}"
          delegate_to: localhost

        - meta: end_host
          when: record_id_healthcheck != ""      

        - name: Display the JSON file content
          shell: cat idem_vm_poweroff_before_gp_check_pre.json
          delegate_to: localhost
          register: result_po_bf_cmdb

        - name: save the Json data to a Variable as a Fact
          set_fact:
            cmdb_po_flag_pre: "{{ result_po_bf_cmdb.stdout[1:-1] }}" 
          delegate_to: localhost

        - meta: end_host
          when: cmdb_po_flag_pre == "F"
               

        - name: Display the JSON file content
          shell: cat idem_cmdb_stat_check_agp.json
          delegate_to: localhost
          register: result_app_cmdb_agp

        - name: save the Json data to a Variable as a Fact
          set_fact:
            cmdb_flag_agp: "{{ result_app_cmdb_agp.stdout[1:-1] }}" 
          delegate_to: localhost

        - meta: end_host
          when: cmdb_flag_agp == "T"

        - name: Display the JSON file content
          shell: cat record_cmdb_stat.json
          delegate_to: localhost
          register: TR_result_cmdb_stat  

        - name: save the Json data to a Variable as a Fact
          set_fact:
            record_id_cmdb_stat: "{{ TR_result_cmdb_stat.stdout[1:-1] }}"
          delegate_to: localhost

        - name: Sleep for 20 seconds and continue with play
          ansible.builtin.wait_for:
            timeout: 20
          delegate_to: localhost
          when: record_id_cmdb_stat == ""                          
             
        - name: VM_host list
          shell: cat host_list_cmdb_agp.yml
          delegate_to: localhost
          register: hostlist_vm              

        - name: save the vm list to a Variable as a Fact
          set_fact:
            vm_hostlist: "{{ hostlist_vm.stdout[:-1] }}" 
          delegate_to: localhost 

        - meta: end_host
          when: vm_hostlist == ""

        - name: Display the JSON file content
          shell: cat winaproach_category.yml
          delegate_to: localhost
          register: result_winaproach_category

        - name: save the Json data to a Variable as a Fact
          set_fact:
            win_category: "{{ result_winaproach_category.stdout }}" 
          delegate_to: localhost 

        - name: Display the JSON file content
          shell: cat bird_api.yml
          delegate_to: localhost
          register: result_bird

        - name: save the Json data to a Variable as a Fact
          set_fact:
            bird_api: "{{ result_bird.stdout }}" 
          delegate_to: localhost                     

        - name: TR creation for CMDB status check task 
          create_tr_bird:
            username: "{{ btmp_user }}"
            password: "{{ btmp_password }}"
            bird: "{{ bird_api }}"
            template_name: "vm deco cmdb status check"
            cr_id: "{{ cr }}"
            ticket_title: "CSTY:DECO:DCAT: VM DECO : cmdb status check after grace period"
            ci: "{{ vm_hostlist }}"
            winaproach_category: "{{ win_category }}"
          register: ticket_id_cmdb_stat
          delegate_to: localhost
          when: record_id_cmdb_stat == ""
           

        - set_fact:
            record_id_cmdb_status: "{{ticket_id_cmdb_stat.id.ticketId}}"
          when: record_id_cmdb_stat == ""    

    
        - copy:
            content: '{{ record_id_cmdb_status|to_json }}'
            dest: record_cmdb_stat.json
          delegate_to: localhost
          when: record_id_cmdb_stat == ""

      rescue:
        - debug:
            msg: "Retried and Failed to Create VM DECO - CMDB status check TR"

    - name: "Handling Create TR- Win@proach for CMDB status check task-Retry 2 "
      block: 

        - name: Display the JSON file content
          shell: cat record_healthcheck.json
          delegate_to: localhost
          register: TR_result_healthcheck  

        - name: save the Json data to a Variable as a Fact
          set_fact:
            record_id_healthcheck: "{{ TR_result_healthcheck.stdout[1:-1] }}"
          delegate_to: localhost

        - meta: end_host
          when: record_id_healthcheck != ""


        - name: Display the JSON file content
          shell: cat idem_vm_poweroff_before_gp_check_pre.json
          delegate_to: localhost
          register: result_po_bf_cmdb

        - name: save the Json data to a Variable as a Fact
          set_fact:
            cmdb_po_flag_pre: "{{ result_po_bf_cmdb.stdout[1:-1] }}" 
          delegate_to: localhost

        - meta: end_host
          when: cmdb_po_flag_pre == "F"
    

        - name: Display the JSON file content
          shell: cat idem_cmdb_stat_check_agp.json
          delegate_to: localhost
          register: result_app_cmdb_agp

        - name: save the Json data to a Variable as a Fact
          set_fact:
            cmdb_flag_agp: "{{ result_app_cmdb_agp.stdout[1:-1] }}" 
          delegate_to: localhost

        - meta: end_host
          when: cmdb_flag_agp == "T"

        - name: Display the JSON file content
          shell: cat record_cmdb_stat.json
          delegate_to: localhost
          register: TR_result_cmdb_stat  

        - name: save the Json data to a Variable as a Fact
          set_fact:
            record_id_cmdb_stat: "{{ TR_result_cmdb_stat.stdout[1:-1] }}"
          delegate_to: localhost

        - name: Sleep for 20 seconds and continue with play
          ansible.builtin.wait_for:
            timeout: 20
          delegate_to: localhost
          when: record_id_cmdb_stat == ""                            

        - name: VM_host list
          shell: cat host_list_cmdb_agp.yml
          delegate_to: localhost
          register: hostlist_vm              

        - name: save the vm list to a Variable as a Fact
          set_fact:
            vm_hostlist: "{{ hostlist_vm.stdout[:-1] }}" 
          delegate_to: localhost 

        - meta: end_host
          when: vm_hostlist == ""

        - name: Display the JSON file content
          shell: cat winaproach_category.yml
          delegate_to: localhost
          register: result_winaproach_category

        - name: save the Json data to a Variable as a Fact
          set_fact:
            win_category: "{{ result_winaproach_category.stdout }}" 
          delegate_to: localhost 

        - name: Display the JSON file content
          shell: cat bird_api.yml
          delegate_to: localhost
          register: result_bird

        - name: save the Json data to a Variable as a Fact
          set_fact:
            bird_api: "{{ result_bird.stdout }}" 
          delegate_to: localhost                     

        - name: TR creation for CMDB status check task 
          create_tr_bird:
            username: "{{ btmp_user }}"
            password: "{{ btmp_password }}"
            bird: "{{ bird_api }}"
            template_name: "vm deco cmdb status check"
            cr_id: "{{ cr }}"
            ticket_title: "CSTY:DECO:DCAT: VM DECO : cmdb status check after grace period"
            ci: "{{ vm_hostlist }}"
            winaproach_category: "{{ win_category }}"
          register: ticket_id_cmdb_stat
          delegate_to: localhost
          when: record_id_cmdb_stat == ""
        

        - set_fact:
            record_id_cmdb_status: "{{ticket_id_cmdb_stat.id.ticketId}}"
          when: record_id_cmdb_stat == ""  
    
    
        - copy:
            content: '{{ record_id_cmdb_status|to_json }}'
            dest: record_cmdb_stat.json
          delegate_to: localhost
          when: record_id_cmdb_stat == ""

      rescue:
        - debug:
            msg: "Retried and Failed to Create VM DECO - CMDB status check TR"                        

    - name: "Handling Start Implementation- Win@proach "
      block:

        - name: Display the JSON file content
          shell: cat record_healthcheck.json
          delegate_to: localhost
          register: TR_result_healthcheck  

        - name: save the Json data to a Variable as a Fact
          set_fact:
            record_id_healthcheck: "{{ TR_result_healthcheck.stdout[1:-1] }}"
          delegate_to: localhost

        - meta: end_host
          when: record_id_healthcheck != ""      

        - name: Display the JSON file content
          shell: cat record_cmdb_stat.json
          delegate_to: localhost
          register: TR_result_cmdb_stat  

        - name: save the Json data to a Variable as a Fact
          set_fact:
            record_id_cmdb_stat: "{{ TR_result_cmdb_stat.stdout[1:-1] }}"
          delegate_to: localhost         

        - meta: end_host
          when: record_id_cmdb_stat == "" 

        - name: Sleep for 62 seconds and continue with play
          ansible.builtin.wait_for:
            timeout: 62
          delegate_to: localhost          

        - name: Start Implementation for CMDB status check TR
          winaproach:
            system: prod
            type: task_record
            operation: start_implementation
            username: "{{ winaproach_username }}"
            password: "{{ winaproach_password }}"
            fields:
              task_id: "{{ record_id_cmdb_stat }}"
          register: start_implementation
          delegate_to: localhost
        
    
      rescue:
        - name: dump test output in the rescue block for CMDB status check
          debug:
            msg: "Failed to Start Implementation on VM DECO - CMDB status check TR :'{{ record_id_cmdb_stat }}'"
