---
- name: "cmdb update"
  hosts: physicaldeco
  gather_facts: no    
  tasks: 
    - name: cmdb update
      ansible.builtin.import_role:
        name: cmdb_update_phy
        tasks_from: filter_hostlist_cmdb_update.yml

- name: "Create TR for cmdb update"
  hosts: localhost
  gather_facts: no
  vars:
    record_id_cmdb_up_phy: ""
    graceperiod_flag: True
    cmdb_update: "F"
    network: "T"
  tasks:
    - name: cmdb update
      ansible.builtin.import_role:
        name: cmdb_update_phy
        tasks_from: create_tr_cmdb_update.yml

- name: "cmdb update"
  hosts: physicaldeco
  gather_facts: no    
  tasks: 
    - name: cmdb update
      ansible.builtin.import_role:
        name: cmdb_update_phy
        tasks_from: cmdb_update.yml
      when: cmdb_update == "F" and network == "T"

- name: "ADD info TR for cmdb update"
  hosts: localhost
  gather_facts: no
  vars:
    record_id_cmdb_up_phy: ""
    graceperiod_flag: True
    cmdb_update: "F"
    network: "T"
  tasks:
    - name: cmdb update
      ansible.builtin.import_role:
        name: cmdb_update_phy
        tasks_from: add_info_cmdb_update.yml

# - name: "cmdb update"
#   hosts: all:vmdeco
#   gather_facts: no    
#   tasks: 
#     - name: cmdb update
#       ansible.builtin.import_role:
#         name: cmdb_update_phy
#         tasks_from: cmdb_logging.yml

# - name: "Logger for cmdb update"
#   hosts: localhost
#   gather_facts: no
#   vars:
    # record_id_cmdb_up_phy: ""
    # graceperiod_flag: True
    # cmdb_update: "F"
    # network: "T"
#   tasks:
#     - name: cmdb update
#       ansible.builtin.import_role:
#         name: cmdb_update_phy
#         tasks_from: logger_cmdb.yml