---
- name: "ilo_reset cleanup"
  hosts: physicaldeco
  gather_facts: no    
  tasks: 
    - name: ilo_reset cleanup
      ansible.builtin.import_role:
        name: ilo_reset
        tasks_from: filter_hostlist_ilo_removal.yml

- name: "Create TR for ilo_reset cleanup"
  hosts: localhost
  gather_facts: no
  vars:
    ilo_reset: "F"
    graceperiod_flag: True
    nvme_cleanup: "T"
  tasks:
    - name: ilo_reset cleanup
      ansible.builtin.import_role:
        name: ilo_reset
        tasks_from: create_tr_ilo.yml

- name: "ilo_reset cleanup"
  hosts: physicaldeco
  gather_facts: no   
  tasks: 
    - name: ilo_reset cleanup
      ansible.builtin.import_role:
        name: ilo_reset
        tasks_from: ilo_reset_main.yml
      when: nvme_cleanup_status == "T" and ilo_reset == "F"

- name: "Add info TR for ilo_reset cleanup"
  hosts: localhost
  gather_facts: no
  vars:   
    graceperiod_flag: True
    ilo_reset: "F"
    backup_remove: "T"
  tasks:
    - name: ilo_reset cleanup
      ansible.builtin.import_role:
        name: ilo_reset
        tasks_from: add_info_ilo.yml