---
- name: "Check output files"
  hosts: localhost
  gather_facts: no    
  tasks: 
    - name: Create result files
      copy:
        dest: "{{ item }}"
        mode: 0644
        content: |
          F
      with_items:
        - idem_cmdb_update_pre.json
        - fqdn_pre.json
        - idem_poweroff_pre.json
        - idem_app_pre.json
        - idem_dns_check_pre.json
        - idem_vmdelete_pre.json 
        - idem_backup_pre.json
        - idem_nas_check_pre.json
        - idem_vm_poweroff_before_gp_check_pre.json
        - idem_cmdb_stat_check_agp_pre.json
        - idem_nas_validate_pre.json
        - idem_vm_stat_cmdb_pre.json
        - idem_filter_domain_pre.json
      no_log: True

    - name: Create result files
      copy:
        dest: "{{ item }}"
        mode: 0644
        content: |
          T
      with_items:
        - idem_cmdb_update.json
        - fqdn.json
        - idem_poweroff.json
        - idem_app.json
        - idem_dns_check.json
        - idem_vmdelete.json
        - idem_backup.json
        - idem_nas_check.json
        - idem_vm_poweroff_before_gp_check.json
        - idem_cmdb_stat_check_agp.json
        - idem_nas_validate.json
        - idem_vm_stat_cmdb.json
        - idem_filter_domain.json
      no_log: True

    - name: generate output files for every module
      file:
        path: "{{ item }}"
        state: touch
        mode: 0644
      with_items:
        - storage_fetch_information_final.txt
        - phy_ssh_failure.txt
        - phy_cmdb_duplicate_failure.txt
        - phy_fqdn_failure.txt
        - phy_cmdb_stat_failure.txt
        - phy_san_info_failure.txt
        - phy_server_gather_info_failure.txt
        - phy_server_shutdown_bgp_failure.txt
        - phy_ilo_poweron_failure.txt
        - phy_ilo_reconf_failure.txt
        - phy_cmdb_stat_failure_agp.txt
        - phy_ilo_reset_failure.txt
        - phy_server_shutdown_agp_failure.txt
        - phy_ipam_failure.txt
        - phy_cmdb_update_failure.txt
        - phy_storage_cleanup_failure.txt
        - cmdb_stat_failure_cmdb_agp_phy.yml
        - cmdb_stat_failure_owner_agp_phy.yml
        - cmdb_stat_failure_cmdb.yml
        - cmdb_stat_failure_owner.yml
        - record_for_server_info_gather.json
        - record_shutdown.json
        - record_shutdown_bgp.json
        - host_list_server_info_gather.yml
        - server_info_success.yml
        - server_info_final.yml
        - server_info_failure.yml
        - file_storage_cleanup_suc_vol.yml
        - record_for_storage_info_fetch.json
        - host_list_storage_info_fetch.yml
        - storage_info_fetch_failure.yml
        - storage_info_fetch_final.yml
        - storage_info_fetch_success.yml
        - record_cmdb_update_phy.json
        - host_list_cmdb_update_phy.yml
        - cmdb_success.yml
        - cmdb_failure.yml
        - cmdb_final.yml
        - host_list_cmdb_fetch_agp_phy.yml
        - cmdb_stat_final_agp_phy.yml
        - record_cmdb_fetch_agp_phy.json
        - cmdb_stat_success_agp_phy.yml
        - cmdb_stat_failure_agp_phy.yml
        - winaproach_category.yml
        - ptr_system.yml
        - record_for_cmdb_dup_info.json
        - cmdb_dup_info_fetch_final.yml
        - host_list_cmdb_duplicate_check.yml
        - cmdb_dup_success.yml
        - cmdb_dup_failure.yml
        - cmdb_final.yml
        - cmdb_success.yml
        - cmdb_failure.yml
        - record_cmdb_update.json
        - host_list_cmdb_update.yml
        - cmdb_stat_success.yml
        - cmdb_stat_failure.yml
        - cmdb_stat_final.yml
        - host_list_cmdb_fetch_bgp.yml
        - storage_account_name.yml
        - record_cmdb_fetch.json
        - failure_storage_controller.yml
        - failure_san.yml
        - record_storage_cleanup.json
        - storage_cleanup_final.yml
        - success_san.yml
        - idem_storage_cleanup.json
        - idem_cmdb_dup_info.json
        - idem_ilo_reconfig.json
        - idem_cmdb_fetch_bgp.json
        - idem_cmdb_fetch_agp_phy.json
        - idem_cmdb_update_phy.json
        - idem_storage_info_fetch.json
        - idem_network.json
        - idem_server_info_gather.json
        - idem_storage_cleanup_pre.json
        - idem_cmdb_dup_info_pre.json
        - idem_ilo_reconfig_pre.json
        - idem_network_pre.json
        - idem_cmdb_fetch_bgp_pre.json
        - idem_cmdb_fetch_agp_phy_pre.json
        - idem_cmdb_update_phy_pre.json
        - idem_storage_info_fetch_pre.json
        - check_artifacts.yml
        - check_final_ssh.yml
        - check_final.yml
        - check_remedy.yml
        - check_artifacts_success.yml
        - phy_shutdown_final.yml
        - shutdown_success.yml
        - shutdown_failure.yml
        - check_final_success.yml
        - check_remedy_success.yml
        - san_switches_success.yml
        - san_switches_fail.yml
        - phy_ssh_success.yml
        - phy_ssh_fail.yml
        - phy_fqdn_fail.yml
        - record_healthcheck_ssh.json
        - record_healthcheck.json
        - record_dns.json
        - cisco_sw_list.yml
        - arista_sw_list.yml
        - net_fail_cisco.yml
        - sw_arista_info.yml
        - sw_arista_info_final.yml
        - record_net_arista.json
        - record_net_cisco.json
        - network_tr_arista.yml
        - network_tr_cisco_fail.yml
        - network_tr_cisco_final.yml
        - net_list.yml
        - host_list_network.yml
        - network_no_sw.yml
        - network_tr_cisco_suc.yml
        - state_file.yml
        - cmdb_url_update.yml
        - cmdb_rtu.yml
        - network_healthcheck_success.yml
        - network_healthcheck_fail.yml
        - phy_dns_success.yml
        - phy_dns_final.yml
        - phy_dns_failure.yml
        - check_ipam.yml
        - check_ipam_success.yml
        - phy_ilo_final.yml
        - ilo_failure.yml
        - ilo_success.yml
        - dns_grid.yml
        - ipam_grid.yml
        - host_list_backup.yml
        - host_list_poweron.yml
        - host_list_shutdown.yml
        - host_list_shutdown_bgp.yml
        - host_list_ilo.yml
        - phy_list.yml
        - info_storage_phy.txt
        - host_list_ilo_reset.yml
        - host_list_ip_dns.yml
        - success_vm_bgp.yml
        - success_vm_agp.yml
        - failure_vm_bgp.yml
        - failure_vm_agp.yml
        - record_vm_logger.json
        - record_id_logger.json
        - phy_dns_win_success.yml
        - record_for_backup.json
        - record_for_poweron.json
        - record_storage_cleanup_phy.json
        - storage_cleanup_final.yml
        - Info_Host_Volume.txt
        - info_san.txt
        - storage_cleanup_success.yml
        - storage_cleanup_failure.yml
        - output_fabric_info.txt
        - info_storage_phy.txt
        - record_ilo.json
        - net_jump.yml
        - net_fail_arista.yml
        - host_list_fqdn_fetch_phy.yml
        - fqdn_failure_phy.yml
        - fqdn_success_phy.yml
        - fqdn_final_phy.yml
        - record_for_fetch_fqdn_ph.json
        - arista_sw_no_list.yml
        - arista_sw_yes_list.yml
        - cisco_sw_no_list.yml
        - cisco_sw_yes_list.yml
        - machinegroups.yml
        - dcm.yml     
        - host_list_firewall.yml
        - record_for_firewall.json
        - phy_list_firewall.yml
        - nvmeout.yml
        - host_list_nvme_cleanup_phy.yml
        - record_for_fetch_nvme_cleanup.json
        - nvmeout.json
        - nvme_failure_phy.yml
        - nvme_success_phy.yml
        - nvme_fin.yml
        - record_for_fetch_nvme_ph.json
        - host_list_nvme_cleanup.yml
        - host_list_ilo_reconfig.yml
        - phy_ilo_reconfigure_final.yml
        - ilo_reconfig_success.yml
        - ilo_reconfig_failure.yml
        - record_ilo_reconfigure.json
      no_log: true