---
    - name: "Check entry for DECO server for filter host list fqdn fetch"
      throttle: 1
      block:
 
        - set_fact:
            host_list: host_list_fqdn_fetch_esxi.yml
          run_once: true


        # - name: Display the JSON file content
        #   shell: cat record_healthcheck.json
        #   delegate_to: localhost
        #   register: TR_result_healthcheck  

        # - name: save the Json data to a Variable as a Fact
        #   set_fact:
        #     record_id_healthcheck: "{{ TR_result_healthcheck.stdout[1:-1] }}"
        #   delegate_to: localhost

        # - meta: end_host
        #   when: record_id_healthcheck != ""
                
        # - name: "Check entry for DECO server for filter hostlist for fqdn fetch"
        #   update_ref_phy:
        #     hostname: "{{inventory_hostname}}"
        #     artifacts_user: "{{ artifacts_user }}"
        #     artifacts_password: "{{ artifacts_password }}"
        #     state_file_url: "{{ state_file}}"
        #     lookup_file_phy: "{{ lookup_file_phy }}"
        #   register: idem_status 
        #   delegate_to: localhost
                 

        # - set_fact: 
        #     cmdb_dup_check: '{{idem_status.module_update.cmdb_dup_check}}'                   
           
        # - set_fact: 
        #     fqdn_info: '{{idem_status.module_update.fqdn_info }}'

      #   - name: "physical server list qualified for fqdn check"
      #     shell: echo "{{ inventory_hostname }}," >> {{ host_list }}                   
      #     delegate_to: localhost
      #     #when: cmdb_dup_check == "T" and fqdn_info == "F"                  

            
      # rescue:
      #   - debug:
            # msg: "Failed to fetch hostlist for FQDN FETCH"      



        - name: "Check entry for DECO server for filter hostlist for FQDN and Vcenter Fetch"
          azure_update_ref_esxi.py:
            connection_string: "{{ private_endpoint_connection_string }}"
            hostname: "{{inventory_hostname}}"
          register: idem_status 
          delegate_to: localhost
                 
        - set_fact: 
            cmdb_dup_check: '{{idem_status.module_update.cmdb_dup_check}}'        

        - set_fact: 
            fqdn_info: '{{idem_status.module_update.fqdn_info}}'            

        - set_fact: 
            vcenter_info: '{{idem_status.module_update.vcenter_info}}'    

        - set_fact: 
            esxi_type: '{{idem_status.module_update.esxi_type}}'              


        - name: Set enclosure name from module update
          set_fact: 
            enclosure_name: '{{ idem_status.module_update.enclosure_name }}'


        # - name: "esxi server list qualified for FQDN Vcenter fetch"
        #   shell: echo "{{ inventory_hostname }}," >> {{ host_list }}                   
        #   delegate_to: localhost
        #   when: cmdb_dup_check == "T" and (esxi_type == "F" or fqdn_info == "F" or vcenter_info == "F" or enclosure_name == "F")
        #   # when: cmdb_dup_check == "T" and (fqdn_info == "F" or vcenter_info == "F")
        #   when: cmdb_dup_check == "T"


        - name: "esxi server list qualified for FQDN Vcenter fetch"
          shell: echo "{{ inventory_hostname }}," >> {{ host_list }}
          delegate_to: localhost
          when:
            - cmdb_dup_check == "T"
            - esxi_type == "F"
              or fqdn_info == "F"
              or vcenter_info == "F"
              or enclosure_name == "F"


           
      rescue:
        - debug:
            msg: "Failed to fetch hostlist for CMDB duplicate check "      
