---
    - name: "Check entry for DECO server"
      block:

        - set_fact:
            host_list: host_list_vcenter.yml

        - name: Display the JSON file content
          shell: cat private_endpoint_connection_string.yml
          delegate_to: localhost
          run_once: true
          register: result_private_endpoint_connection_string
    
        - name: save the Json data to a Variable as a Fact
          set_fact:
            private_endpoint_connection_string: "{{ result_private_endpoint_connection_string.stdout }}"
          run_once: true
          delegate_to: localhost      
                
        - name: "Check entry for DECO server from azure"
          azure_update_ref_esxi:
            connection_string: "{{ private_endpoint_connection_string }}"
            hostname: "{{inventory_hostname}}"
          register: idem_status 
          delegate_to: localhost
        
           

        - set_fact: 
            ipam_cleanup: '{{idem_status.module_update.ipam_cleanup}}'  

        - set_fact: 
            vcenter_cleanup: '{{idem_status.module_update.vcenter_cleanup}}'        

        - name: "ESXi list"
          shell: echo "{{ inventory_hostname }}," >> {{ host_list }}                   
          delegate_to: localhost           
          when: vcenter_cleanup == "F" and ipam_cleanup == "T"  
              

            
      rescue:
        - debug:
            msg: "Failed to fetch hostlist for Enclosure Vcenter Deregister"      

