---
    - name: "Fetching location info for the severs "
      block:
       
        - set_fact:
            host_list: host_list_enclosure_storage.yml

        - name: Display the JSON file content
          shell: cat private_endpoint_connection_string.yml
          delegate_to: localhost
          run_once: true
          register: result_private_endpoint_connection_string
    
        - name: save the Json data to a Variable as a Fact
          set_fact:
            private_endpoint_connection_string: "{{ result_private_endpoint_connection_string.stdout }}"
          run_once: true
          delegate_to: localhost      
                
        - name: "Check entry for DECO server for filter hostlist for DCM module"
          azure_update_ref_esxi:
            connection_string: "{{ private_endpoint_connection_string }}"
            hostname: "{{inventory_hostname}}"
          register: idem_status 
          delegate_to: localhost
 
        - set_fact:
            san_info_fetch: '{{idem_status.module_update.san_info_fetch}}'

        - set_fact:
            dcm: '{{idem_status.module_update.dcm}}'

        - name: "ESXi list"
          shell: echo "{{ inventory_hostname }}," >> {{ host_list }}                   
          delegate_to: localhost               
          when: san_info_fetch == "F" and dcm == "T"
  
 
      rescue:
        - debug:
            msg: "Failed to fetch host  info - Enclosure Storage"