---
# - name: "This playbook is to create PTR for PHYSCIAL deco service health check"
#   hosts: localhost
#   gather_facts: no
           
        
#   tasks:      
#####################################################################################################################        
                               

    - name: "Handling PTR record_id for PHYSCIAL deco"
      block:

        - name: Display the JSON file content
          shell: cat record_healthcheck_ssh.json
          delegate_to: localhost
          register: TR_result_healthcheck  

        - name: save the Json data to a Variable as a Fact
          set_fact:
            record_healthcheck_ssh: "{{ TR_result_healthcheck.stdout[1:-1] }}"
          delegate_to: localhost

        - meta: end_host
          when: record_healthcheck_ssh == ""       

        - name: Display the JSON file content
          shell: cat phy_ssh_fail.yml
          delegate_to: localhost
          register: result_check_linux

        - name: save the Json data to a Variable as a Fact
          set_fact:
            phy_ssh_fail: "{{ result_check_linux.stdout }}" 
          delegate_to: localhost 


        - set_fact:
            form1: "***********************************************************************"
            form2: "Below are the ssh connectivity(linux) issue details which needs support"
            form3: "***********************************************************************"
        - set_fact:
            content_phy_ssh_fail: "{{ form1 +'\n'+ form2 +'\n'+ form3 +'\n'+ phy_ssh_fail }}"
          when: phy_ssh_fail != ""

        - name: Display the JSON file content
          shell: cat record_healthcheck_ssh.json
          delegate_to: localhost
          register: TR_result_healthcheck  

        - name: save the Json data to a Variable as a Fact
          set_fact:
            record_healthcheck_ssh: "{{ TR_result_healthcheck.stdout[1:-1] }}"
          delegate_to: localhost

        - name: Display the JSON file content
          shell: cat winaproach_category.yml
          delegate_to: localhost
          register: result_winaproach_category

        - name: save the Json data to a Variable as a Fact
          set_fact:
            win_category: "{{ result_winaproach_category.stdout }}" 
          delegate_to: localhost

        - name: Display the JSON file content
          shell: cat ptr_system.yml
          delegate_to: localhost
          register: result_ptr_system

        - name: save the Json data to a Variable as a Fact
          set_fact:
            ptr_sys: "{{ result_ptr_system.stdout }}" 
          delegate_to: localhost                    

############################################################################################################
        - name: read yaml file from the specific location 
          set_fact:
            file_content: "{{lookup('file', 'machinegroups.yml')}}"

        - name: split the file content
          set_fact:
            lines: "{{file_content.split('\n')}}"

        - name: convert the lines in the file to dict
          set_fact:
            res_dict: "{{ res_dict | default({}) | combine({ item.split('\t')[0]: item.split('\t')[1] }) }}"
          loop: "{{ lines }}"

        - name: find which key is preset in the log
          set_fact: 
            present_key: "{{ present_key | default([]) + [item] }}"
          loop: "{{ res_dict.keys() }}"
          when: content_phy_ssh_fail is defined and item in content_phy_ssh_fail

        - name: print the corresponded  value of the key present
          set_fact:
            allowner_name: "{{ allowner_name | default({}) | combine({item:res_dict[item]}) }}"
          loop: "{{ present_key }}"
          when: content_phy_ssh_fail is defined

        - name: all owners with format
          set_fact:
            all_owner_Final: | 
              {% for key,value in allowner_name.items()%}
              {{ key }} : {{ value }}
              {% endfor %}
          when: content_phy_ssh_fail is defined

        - set_fact:
            Requester_group: "Requester_group: {{requester_group}}"
            Requester_name: "Requester_name: {{requester_name}}"

        - name: "writing output to File"
          shell: echo -e "{{content_phy_ssh_fail}}\n\n{{Requester_group}}\n{{Requester_name}}\n\nOwner group Details below:\n{{all_owner_Final}}" > groups_ptr.yml
          delegate_to: localhost
          when: content_phy_ssh_fail is defined

        - name: Display the JSON file content
          shell: cat groups_ptr.yml
          delegate_to: localhost
          register: result_groups
          when: content_phy_ssh_fail is defined

        - name: save the Json data to a Variable as a Fact
          set_fact:
            support_groups: "{{ result_groups.stdout }}" 
          delegate_to: localhost 
          when: content_phy_ssh_fail is defined

        - name: Create PTR
          problem_tr:
            win_url: "WIN@PROACH_URL"
            username: "DecoP112686"
            password: "opFCtCpIMzmC"
            ptr_title: "PHYSCIAL DECO: Service health check on SSH connectivity(linux) referring to failed TR - {{ record_healthcheck_ssh }}"
            tr_map: "{{ record_healthcheck_ssh }}"
            assignee_group: "OLINUX1"  
            ptr_logs: "{{ support_groups }}"
            winaproach_category: "{{ win_category }}"
            ptr_system: "{{ ptr_sys }}"         
          register: ptr_phy_ssh_fail
          until: '"Successfully" in ptr_phy_ssh_fail.msg'
          retries: 3
          delay: 10
          when: phy_ssh_fail != ""

        - name: Display the JSON file content
          shell: cat private_endpoint_connection_string.yml
          delegate_to: localhost
          register: result_private_endpoint_connection_string

        - name: save the Json data to a Variable as a Fact
          set_fact:
            private_endpoint_connection_string: "{{ result_private_endpoint_connection_string.stdout }}"
          delegate_to: localhost

        - name: Get timestamp from the system
          shell: "date +%Y-%m-%d/%H:%M"
          delegate_to: localhost
          register: tstamp  

        - set_fact:
            time: "{{tstamp.stdout}}"

        - name: filter owner group
          categorize_servers:
            path: phy_ssh_failure.txt
          delegate_to: localhost
          register: failure_servers_list
          when: phy_ssh_fail != ""

        - debug:
            var: failure_servers_list
          when: phy_ssh_fail != ""

        - name: "Send data to azure table"
          send_ptr_info_to_azure:
            ci: "{{ item }}"
            cr: "{{ cr }}"
            event_number: "{{ ptr_phy_ssh_fail.id }}"
            event: "Physical DECO: Service health check on SSH connectivity(linux) failure"
            event_status: "open"
            created_on: "{{ time }}"
            last_update: "{{ time }}"
            connection_string: "{{ private_endpoint_connection_string }}" 
          loop: "{{ failure_servers_list.Status.Failure }}"  
          register: ptr_add
          when: phy_ssh_fail != ""

        - name: Update TR with PTR
          tr_overview:
            win_url: "WIN@PROACH_URL"
            username: "DecoP112686"
            password: "opFCtCpIMzmC"
            task_id: "{{ record_healthcheck_ssh }}"
            prob_id: "{{ ptr_phy_ssh_fail.id }}"                   
          register: update_overview  
          when: phy_ssh_fail != "" 

      rescue:
        - debug:
            msg: "Exception occurred PTR service health check - SSH connectivity(linux)"                               
############################################################################################################

