---
    - name: "Check entry for DECO server"
      throttle: 1
      block:
        - set_fact:
            host_list: host_list_backup.yml    

        - name: Display the JSON file content
          shell: cat private_endpoint_connection_string.yml
          delegate_to: localhost
          register: result_private_endpoint_connection_string
    
        - name: save the Json data to a Variable as a Fact
          set_fact:
            private_endpoint_connection_string: "{{ result_private_endpoint_connection_string.stdout }}"
          delegate_to: localhost

        - name: "Check entry for DECO server"
          azure_update_ref:
            connection_string: "{{ private_endpoint_connection_string }}"
            hostname: "{{inventory_hostname}}"
          register: idem_status
          delegate_to: localhost


        - set_fact: 
            backup_status: '{{ idem_status.module_update.backup }}' 

        - set_fact: 
            cmdb_stat_check_agp: '{{idem_status.module_update.cmdb_stat_check_agp}}'      


        - name: "VM list"
          shell: echo "{{ inventory_hostname }}," >> {{ host_list }}                   
          delegate_to: localhost
          when: backup_status == "F" and cmdb_stat_check_agp == "T"
                            

      rescue:
        - debug:
            msg: "Failed to fect hostlist for backup"    

