---
    - name: "Check entry for DECO server"
      throttle: 1    
      block:

        - set_fact:
            host_list: "host_list_cmdb_update.yml" 

        - name: Display the JSON file content
          shell: cat private_endpoint_connection_string.yml
          delegate_to: localhost
          register: result_private_endpoint_connection_string
    
        - name: save the Json data to a Variable as a Fact
          set_fact:
            private_endpoint_connection_string: "{{ result_private_endpoint_connection_string.stdout }}"
          delegate_to: localhost       

        - name: "Check entry for DECO server"
          azure_update_ref:
            connection_string: "{{ private_endpoint_connection_string }}"
            hostname: "{{inventory_hostname}}"
          register: idem_status
          delegate_to: localhost
         

        - set_fact: 
            cmdb_check: '{{idem_status.module_update.cmdb}}'

        - set_fact: 
            vmdelete: '{{idem_status.module_update.vm_delete}}'                           
           

        - name: "VM list"
          shell: echo "{{ inventory_hostname }}," >> {{ host_list }}                   
          delegate_to: localhost
          when: cmdb_check == "F" and vmdelete == "T"                 

            
      rescue:
        - debug:
            msg: "Failed to fect hostlist for CMDB update"      

