---
# - name: "This playbook is to Create TR for CMDB duplicate check task"
#   hosts: all
#   gather_facts: no
#   vars:
#     record_cmdb_dup_info: ""
#     graceperiod_flag: false
#     cmdb_dup_check: False   #### state file variable
#     backup: true  ### state file variable of previous module


  # tasks: 
    - name: "Handling Create TR- Win@proach for CMDB duplicate check  "
      block: 
        - name: Display the JSON file content
          shell: cat record_healthcheck.json
          delegate_to: localhost
          register: TR_result_healthcheck  

        - name: save the Json data to a Variable as a Fact
          set_fact:
            record_id_healthcheck: "{{ TR_result_healthcheck.stdout[1:-1] }}"
          delegate_to: localhost

        - meta: end_host
          when: record_id_healthcheck != ""      

        - name: esxi_host list
          shell: cat host_list_cmdb_duplicate_check.yml
          delegate_to: localhost
          register: hostlist_esxi             

        - name: save the esxi list to a Variable as a Fact
          set_fact:
            esxi_hostlist: "{{ hostlist_esxi.stdout[:-1] }}" 
          delegate_to: localhost 

        - meta: end_host
          when: esxi_hostlist == ""       

        - name: "Custom module [CREATE TR]"
          create_tr:
            record_type: "TR"
            title: "CSTY:DECO:DCAT: ESXI RACK DECO - CMDB duplicate check"
            assignee_name: "DecoP112686"
            assignee_group: "DINFDECO"   #"DINFDECO"            
            severity: "4"
            overview: "esxi DECO - CMDB duplicate check"
            parent_id: "{{ cr }}"            
            username: "{{ winaproach_username }}"     
            password: "{{ winaproach_password }}"
          delegate_to: localhost  
          no_log: False
          register: create_tr_output
       
        - set_fact:
            record_cmdb_dup_info: "{{create_tr_output.record_id}}"

        - copy:
            content: '{{ record_cmdb_dup_info|to_json }}'
            dest: record_for_cmdb_dup_info.json
          delegate_to: localhost

        - name: adding documentation tag
          tr_documentation:
            username: "{{ winaproach_username }}"    
            password: "{{ winaproach_password }}"
            win_url: "{{win_url}}"
            task_id: "{{ record_cmdb_dup_info }}"
          register: add_document
          delegate_to: localhost

      rescue:
        - debug:
            msg: "Failed to Create esxi DECO - for CMDB duplicate check "

    - name: "Handling Create TR- Win@proach forStorage info fetch- Retry 1"
      block:

        - name: Display the JSON file content
          shell: cat record_healthcheck.json
          delegate_to: localhost
          register: TR_result_healthcheck  

        - name: save the Json data to a Variable as a Fact
          set_fact:
            record_id_healthcheck: "{{ TR_result_healthcheck.stdout[1:-1] }}"
          delegate_to: localhost

        - meta: end_host
          when: record_id_healthcheck != ""      

        - name: esxi_host list
          shell: cat host_list_cmdb_duplicate_check.yml
          delegate_to: localhost
          register: hostlist_esxi              

        - name: save the esxi list to a Variable as a Fact
          set_fact:
            esxi_hostlist: "{{ hostlist_esxi.stdout[:-1] }}" 
          delegate_to: localhost 

        - meta: end_host
          when: esxi_hostlist == ""

        - name: Display the JSON file content
          shell: cat record_for_cmdb_dup_info.json
          delegate_to: localhost
          register: TR_result
    
        - name: save the Json data to a Variable as a Fact
          set_fact:
            record_for_cmdb_dup_info: "{{ TR_result.stdout[1:-1] }}" 
          delegate_to: localhost          


        - name: Sleep for 20 seconds and continue with play
          ansible.builtin.wait_for:
            timeout: 20
          delegate_to: localhost
          when: record_for_cmdb_dup_info == "" 

        - name: "Custom module [CREATE TR]"
          create_tr:
            record_type: "TR"
            title: "CSTY:DECO:DCAT: ESXI RACK DECO - CMDB duplicate check"
            assignee_name: "DecoP112686"
            assignee_group: "DINFDECO"   #"DINFDECO"            
            severity: "4"
            overview: "esxi DECO - CMDB duplicate check"
            parent_id: "{{ cr }}"            
            username: "{{ winaproach_username }}"     
            password: "{{ winaproach_password }}"
          delegate_to: localhost  
          no_log: False
          register: create_tr_output
          when: record_for_cmdb_dup_info == "" 

        - set_fact:
            record_cmdb_dup_info: "{{create_tr_output.record_id}}"
          when: record_for_cmdb_dup_info == "" 

        - copy:
            content: '{{ record_cmdb_dup_info|to_json }}'
            dest: record_for_cmdb_dup_info.json
          delegate_to: localhost
          when: create_tr_output is defined

        - name: adding documentation tag
          tr_documentation:
            username: "{{ winaproach_username }}"    
            password: "{{ winaproach_password }}"
            win_url: "{{win_url}}"
            task_id: "{{ record_cmdb_dup_info }}"
          register: add_document
          delegate_to: localhost
          when: record_for_cmdb_dup_info == "" 

      rescue:
        - debug:
            msg: "Retried and Failed to Create esxi DECO -for CMDB duplicate check TR"

    - name: "Handling Create TR- Win@proach for for CMDB duplicate check -Retry 2 "
      block:

        - name: Display the JSON file content
          shell: cat record_healthcheck.json
          delegate_to: localhost
          register: TR_result_healthcheck  

        - name: save the Json data to a Variable as a Fact
          set_fact:
            record_id_healthcheck: "{{ TR_result_healthcheck.stdout[1:-1] }}"
          delegate_to: localhost

        - meta: end_host
          when: record_id_healthcheck != ""      

        - name: esxi_host list
          shell: cat host_list_cmdb_duplicate_check.yml
          delegate_to: localhost
          register: hostlist_esxi              

        - name: save the esxi list to a Variable as a Fact
          set_fact:
            esxi_hostlist: "{{ hostlist_esxi.stdout[:-1] }}" 
          delegate_to: localhost 

        - meta: end_host
          when: esxi_hostlist == ""

        - name: Display the JSON file content
          shell: cat record_for_cmdb_dup_info.json
          delegate_to: localhost
          register: TR_result
    
        - name: save the Json data to a Variable as a Fact
          set_fact:
            record_for_cmdb_dup_info: "{{ TR_result.stdout[1:-1] }}" 
          delegate_to: localhost          


        - name: Sleep for 20 seconds and continue with play
          ansible.builtin.wait_for:
            timeout: 20
          delegate_to: localhost
          when: record_for_cmdb_dup_info == "" 

        - name: "Custom module [CREATE TR]"
          create_tr:
            record_type: "TR"
            title: "CSTY:DECO:DCAT: ESXI RACK DECO - CMDB duplicate check"
            assignee_name: "DecoP112686"
            assignee_group: "DINFDECO"   #"DINFDECO"            
            severity: "4"
            overview: "esxi DECO - CMDB duplicate check"
            parent_id: "{{ cr }}"            
            username: "{{ winaproach_username }}"     
            password: "{{ winaproach_password }}"
          delegate_to: localhost  
          no_log: False
          register: create_tr_output
          when: record_for_cmdb_dup_info == "" 

        - set_fact:
            record_cmdb_dup_info: "{{create_tr_output.record_id}}"
          when: record_for_cmdb_dup_info == "" 

        - copy:
            content: '{{ record_cmdb_dup_info|to_json }}'
            dest: record_for_cmdb_dup_info.json
          delegate_to: localhost
          when: create_tr_output is defined

        - name: adding documentation tag
          tr_documentation:
            username: "{{ winaproach_username }}"    
            password: "{{ winaproach_password }}"
            win_url: "{{win_url}}"
            task_id: "{{ record_cmdb_dup_info }}"
          register: add_document
          delegate_to: localhost
          when: record_for_cmdb_dup_info == "" 
          
      rescue:
        - debug:
            msg: "Retried and Failed to Create esxi DECO - CMDB duplicate check  TR"                        
