---    
        
    - name: "Handling TR record_id to update and close the TR for instance id fetch"
      block:
      
        - set_fact: 
            file_instanceid_fin : "instanceid_final.yml" 
            file_instanceid: "instanceid_success.yml"
            file_instanceid_fail: "instanceid_fail.yml"                       

        - name: Display the JSON file content
          shell: cat record_healthcheck.json
          delegate_to: localhost
          register: TR_result_healthcheck  

        - name: save the Json data to a Variable as a Fact
          set_fact:
            record_id_healthcheck: "{{ TR_result_healthcheck.stdout[1:-1] }}"
          delegate_to: localhost

        - meta: end_host
          when: record_id_healthcheck != ""       

        - name: Display the JSON file content
          shell: cat record_for_instanceid.json
          delegate_to: localhost
          register: TR_result_instanceid 

        - name: save the Json data to a Variable as a Fact
          set_fact:
            record_id_instanceid: "{{ TR_result_instanceid.stdout[1:-1] }}"
          delegate_to: localhost         

        - meta: end_host
          when: record_id_instanceid == ""      

        - name: Display the JSON file content
          shell: cat idem_instanceid.json
          delegate_to: localhost
          register: result_instanceid

        - name: save the Json data to a Variable as a Fact
          set_fact:
            instanceid_flag: "{{ result_instanceid.stdout[1:-1] }}" 
          delegate_to: localhost
         

        - meta: end_host
          when: instanceid_flag == "T" 

 #############  success info gathering ##########################
        - name : handling error in the success block
          block:
            - name: Display the JSON file content
              shell: cat instanceid_success.yml
              delegate_to: localhost
              register: result_instanceid_suc

            - name: save the Json data to a Variable as a Fact
              set_fact:
                result_instanceid_suc_v: "{{ result_instanceid_suc.stdout }}" 
              delegate_to: localhost  
      
            
            - set_fact:
                form1: "***********************************************************************"
                form2: "Below are the DECO results for instance ID fetch - VMs"
                form3: "***********************************************************************"
            - set_fact:
                content_instanceid_suc: "{{ form1 +'\n'+ form2 +'\n'+ form3 +'\n'+ result_instanceid_suc_v }}" 
              when: result_instanceid_suc_v != ""  


            - name: " Merge Success information to single final file "
              shell: echo "{{content_instanceid_suc}}" >> instanceid_final.yml                    
              delegate_to: localhost
              when: result_instanceid_suc_v != "" 

          rescue:
            - debug:
                msg: "Rescue for no success file found and continue"   
                   
  ####################### Failure info gathering ########################## 
        - name : handling error in the failure block
          block:          
            - name: Display the JSON file content
              shell: cat instanceid_fail.yml
              delegate_to: localhost
              register: result_instanceid_fail

            - name: save the Json data to a Variable as a Fact
              set_fact:
                result_instanceid_fail_v: "{{ result_instanceid_fail.stdout }}" 
              delegate_to: localhost  
    
            
            - set_fact:
                form1: "***********************************************************************"
                form2: "Below are the DECO results for instance ID fetch - VMs"
                form3: "***********************************************************************"
            - set_fact:
                content_instanceid_fail: "{{ form1 +'\n'+ form2 +'\n'+ form3 +'\n'+ result_instanceid_fail_v }}"
              when: result_instanceid_fail_v != ""    
       
            - name: " Merge Failure information to to single final file"
              shell: echo "{{ content_instanceid_fail }}" >> instanceid_final.yml                    
              delegate_to: localhost
              when: result_instanceid_fail_v != ""

          rescue:
            - debug:
                msg: "Rescue for no failure file found and continue"

##########################  merging both failure and success results ###########################

        - name: Display the JSON file content
          shell: cat instanceid_final.yml
          delegate_to: localhost
          register: result_instanceid_fin

        - name: save the Json data to a Variable as a Fact
          set_fact:
            result_instanceid_fin_v: "{{ result_instanceid_fin.stdout }}" 
          delegate_to: localhost  


########################   results added to TR  ############################################
        - name: "add message to failed TR"
          add_message_to_tr:
            record_id: "{{record_for_instanceid}}"
            message: "{{ result_instanceid_fin_v }}"             
            username: "{{ winaproach_username }}"
            password: "{{ winaproach_password }}"
          delegate_to: localhost
          register: add_msg_output 
          
        - name: Display the JSON file content
          shell: cat winaproach_category.yml
          delegate_to: localhost
          register: result_winaproach_category

        - name: save the Json data to a Variable as a Fact
          set_fact:
            win_category: "{{ result_winaproach_category.stdout }}" 
          delegate_to: localhost

        - name: Display the JSON file content
          shell: cat ptr_system.yml
          delegate_to: localhost
          register: result_ptr_system

        - name: save the Json data to a Variable as a Fact
          set_fact:
            ptr_sys: "{{ result_ptr_system.stdout }}" 
          delegate_to: localhost             

################################ PTR creation ###################################
        - name: Create PTR
          problem_tr:
            win_url: "WIN@PROACH_URL"
            username: "{{ winaproach_username }}"
            password: "{{ winaproach_password }}"
            ptr_title: "VM DECO: instance id fetch details with failed TR - {{ record_for_instanceid }}"
            tr_map: "{{ record_for_instanceid }}"
            assignee_group: "OSP000"  
            ptr_logs: "{{ content_instanceid_fail }}"
            winaproach_category: "{{ win_category }}"
            ptr_system: "{{ ptr_sys }}"          
          register: ptr_out_instance
          until: '"Successfully" in ptr_out_instance.msg'
          retries: 3
          delay: 10
          when: result_instanceid_fin_v is search("ERROR")

        - name: Display the JSON file content
          shell: cat private_endpoint_connection_string.yml
          delegate_to: localhost
          register: result_private_endpoint_connection_string

        - name: save the Json data to a Variable as a Fact
          set_fact:
            private_endpoint_connection_string: "{{ result_private_endpoint_connection_string.stdout }}"
          delegate_to: localhost

        - name: Get timestamp from the system
          shell: "date +%Y-%m-%d/%H:%M"
          delegate_to: localhost
          register: tstamp  

        - set_fact:
            time: "{{tstamp.stdout}}"

        - name: filter owner group
          categorize_servers:
            path: instanceid_failure_vm.txt
          delegate_to: localhost
          register: failure_servers_list
          when: result_instanceid_fin_v is search("ERROR")

        - debug:
            var: failure_servers_list
          when: result_instanceid_fin_v is search("ERROR")

        - name: "Send data to azure table"
          send_ptr_info_to_azure:
            ci: "{{ item }}"
            cr: "{{ cr }}"
            event_number: "{{ ptr_out_instance.id }}"
            event: "VM DECO: Fetch instance id failure"
            event_status: "open"
            created_on: "{{ time }}"
            last_update: "{{ time }}"
            connection_string: "{{ private_endpoint_connection_string }}" 
          loop: "{{ failure_servers_list.Status.Failure }}"
          register: ptr_add
          when: result_instanceid_fin_v is search("ERROR")

        - name: Update TR with PTR
          tr_overview:
            win_url: "WIN@PROACH_URL"
            username: "{{ winaproach_username }}"
            password: "{{ winaproach_password }}"
            task_id: "{{ record_for_instanceid }}"
            prob_id: "{{ ptr_out_instance.id }}"                   
          register: update_overview  
          when: result_instanceid_fin_v is search("ERROR")

############################# closing TR  ####################            
        - name: "Test custome module [CLOSE TR]"
          close_tr:
            record_id: "{{record_for_instanceid}}"
            username: "{{ winaproach_username }}"
            password: "{{ winaproach_password }}"
          register: close_tr_output
       
      rescue:
        - debug:
            msg: "Exception occurred so rescued the main tr result block for instance id fetch"