---
    - name: "Check entry for DECO server"
      throttle: 1
      block:
 
        - set_fact:
            host_list: host_list_filter_domain.yml

        - name: Display the JSON file content
          shell: cat private_endpoint_connection_string.yml
          delegate_to: localhost
          register: result_private_endpoint_connection_string
    
        - name: save the Json data to a Variable as a Fact
          set_fact:
            private_endpoint_connection_string: "{{ result_private_endpoint_connection_string.stdout }}"
          delegate_to: localhost
                
        - name: "Check entry for DECO server"
          azure_update_ref:
            connection_string: "{{ private_endpoint_connection_string }}"
            hostname: "{{inventory_hostname}}"
          register: idem_status
          delegate_to: localhost
                 

        - set_fact: 
            filter_domain: '{{idem_status.module_update.filter_domain}}'

        - set_fact: 
            instanceid: '{{idem_status.module_update.instanceid}}'           

        - name: "VM list"
          shell: echo "{{ inventory_hostname }}," >> {{ host_list }}                   
          delegate_to: localhost
          when: filter_domain == "F" and instanceid != "F"                   

            
      rescue:
        - debug:
            msg: "Failed to fetch hostlist for filter domain for netapp and dts"      

