=============================================================
=============================================================
[brocade_fab_E1a]
mucfsps11088 server_ip=10.82.108.151 fabric=FabricE1a
=============================================================