=============================================================
=============================================================
[brocade_fab_E1a]
mucfsps11088 server_ip=10.82.111.13 fabric=FabricE1a
=============================================================
=============================================================
[brocade_fab_E3a]
mucfsps31043 server_ip=10.82.108.193 fabric=FabricE3a
=============================================================
=============================================================
[brocade_fab_a_E4a]
mucfsps45019 server_ip=10.82.108.247 fabric=FabricE4a
=============================================================
=============================================================
[brocade_fab_F2a]
frafsps21019 server_ip=10.100.2.42   fabric=FabricF2a
=============================================================
[brocade_fab_F3a]
frafsps31019 server_ip=10.100.2.62   fabric=FabricF3a
=============================================================
=============================================================
[brocade_fab_S1a]
mucfsphS1057 server_ip=10.82.113.31  fabric=FabricS1a
=============================================================
[brocade_fab_S2a]
mucfsphT3067 server_ip=10.82.113.37  fabric=FabricS2a
=============================================================
[brocade_fab_S3a]
mucfsphU5077 server_ip=10.82.113.46  fabric=FabricS3a
=============================================================
=============================================================
[brocade_fab_P1a]
mucfspsA1012 server_ip=10.82.108.253 fabric=FabricP1a
=============================================================
[brocade_fab_P2a]
mucfspsB2020 server_ip=10.82.109.5   fabric=FabricP2a
=============================================================
[brocade_fab_P3a]
mucfspsC3030 server_ip=10.82.109.11  fabric=FabricP3a
=============================================================
[brocade_fab_P4a]
mucfspsD4042 server_ip=10.82.109.17  fabric=FabricP4a
=============================================================
[brocade_fab_P5a]
mucfspsE5052 server_ip=10.82.109.23  fabric=FabricP5a
=============================================================
[brocade_fab_P6a]
mucfspsF6059 server_ip=10.82.109.29  fabric=FabricP6a
=============================================================
=============================================================
[brocade_fab_M1a]
mucfspsm5070 server_ip=10.82.110.206 fabric=FabricM1a
=============================================================
[brocade_fab_N1a]
mucfspeN1075 server_ip=10.82.110.59  fabric=FabricN1a
=============================================================
=============================================================

=============================================================
=============================================================
[brocade_fab_E1b]
mucfsps14188 server_ip=10.82.111.16  fabric=FabricE1b
=============================================================
=============================================================
[brocade_fab_b_E3b]
mucfsps32163 server_ip=10.82.108.196 fabric=FabricE3b
=============================================================
=============================================================
[brocade_fab_b_E4b]
mucfsps42119 server_ip=10.82.108.238 fabric=FabricE4b
=============================================================
=============================================================
[brocade_fab_F2b]
frafsps21119 server_ip=10.100.2.52   fabric=FabricF2b
=============================================================
[brocade_fab_F3b]
frafsps31119 server_ip=10.100.2.72   fabric=FabricF3b
=============================================================
=============================================================
[brocade_fab_S1b]
mucfsphS4157 server_ip=10.82.113.34  fabric=FabricS1b
=============================================================
[brocade_fab_S2b]
mucfsphT6167 server_ip=10.82.113.40  fabric=FabricS2b
=============================================================
[brocade_fab_S3b]
mucfsphU2177 server_ip=10.82.113.43  fabric=FabricS3b
=============================================================
=============================================================
[brocade_fab_P1b]
mucfspsA1112 server_ip=10.82.109.2   fabric=FabricP1b
=============================================================
[brocade_fab_P2b]
mucfspsB2120 server_ip=10.82.109.8   fabric=FabricP2b
=============================================================
[brocade_fab_P3b]
mucfspsC3130 server_ip=10.82.109.14  fabric=FabricP3b
=============================================================
[brocade_fab_P4b]
mucfspsD4142 server_ip=10.82.109.20  fabric=FabricP4b
=============================================================
[brocade_fab_P5b]
mucfspsE5152 server_ip=10.82.109.26  fabric=FabricP5b
=============================================================
[brocade_fab_P6b]
mucfspsF6159 server_ip=10.82.109.32  fabric=FabricP6b
=============================================================
=============================================================
[brocade_fab_M1b]
mucfspsm4170 server_ip=10.82.110.209 fabric=FabricM1b
=============================================================
[brocade_fab_b_N1b]
mucfspeN4175 server_ip=10.82.110.62  fabric=FabricN1b
=============================================================
=============================================================
