---
- name: "cmdb update"
  hosts: "{{ target_hosts }}"
  gather_facts: no    
  tasks: 
    - name: cmdb update
      ansible.builtin.import_role:
        name: cmdb_update_esxi
        tasks_from: filter_hostlist_cmdb_update.yml

- name: "Create TR for cmdb update"
  hosts: localhost
  gather_facts: no
  vars:
    bird_api: "{{ hostvars['localhost']['config_data']['bird_api'] }}"
    win_category: "{{ hostvars['localhost']['config_data']['winaproach_category'] }}"

  tasks:
    - name: Set local variables from config_data
      set_fact:
        bird_api: "{{ config_data.bird_api }}"
        win_category: "{{ config_data.winaproach_category }}"

        
    - name: cmdb update
      ansible.builtin.import_role:
        name: cmdb_update_esxi
        tasks_from: create_tr_cmdb_update.yml

- name: "cmdb update"
  hosts: "{{ target_hosts }}"
  gather_facts: no    
  vars:
    instanceid: ""
    cmdb_url_update: "{{ hostvars['localhost']['config_data']['cmdb_url_update'] }}"

  tasks: 
    - name: cmdb update
      ansible.builtin.import_role:
        name: cmdb_update_esxi
        tasks_from: cmdb_update.yml

- name: "ADD info TR for cmdb update"
  hosts: localhost
  gather_facts: no
  vars:
    win_category: "{{ hostvars['localhost']['config_data']['winaproach_category'] }}"
    ptr_sys: "{{ hostvars['localhost']['config_data']['ptr_system'] }}"
  tasks:
    - name: Set local variables from config_data
      set_fact:
        ptr_sys: "{{ config_data.ptr_system }}"
        win_category: "{{ config_data.winaproach_category }}"

    - name: cmdb update
      ansible.builtin.import_role:
        name: cmdb_update_esxi
        tasks_from: add_info_cmdb_update.yml

# - name: "cmdb update"
#   hosts: all:vmdeco
#   gather_facts: no    
#   tasks: 
#     - name: cmdb update
#       ansible.builtin.import_role:
#         name: cmdb_update_esxi
#         tasks_from: cmdb_logging.yml

# - name: "Logger for cmdb update"
#   hosts: localhost
#   gather_facts: no
#   vars:
    # record_id_cmdb_up_phy: ""
    # graceperiod_flag: True
    # cmdb_update: "F"
    # network: "T"
#   tasks:
#     - name: cmdb update
#       ansible.builtin.import_role:
#         name: cmdb_update_esxi
#         tasks_from: logger_cmdb.yml