---
- name: "failure handler test"
  hosts: all:esxideco_rack
  gather_facts: no
  tasks:
    - name: grouping
      ansible.builtin.import_role:
        name: grouping
        tasks_from: owner_grouping