---

- name: "success/Failure logs"
  # hosts: enclosures
  hosts: esxideco_rack
  gather_facts: no    
  tasks: 

    - name: success/Failure logs
      ansible.builtin.import_role:
        name: deco_logging_rack
        tasks_from: success_fail_doc.yml
        

- name: "Create TR for success/Failure logs"
  hosts: localhost
  gather_facts: no
  # vars:
  #   graceperiod_flag: True 
  tasks:

    - name: success/Failure logs
      ansible.builtin.import_role:
        name: deco_logging_rack
        tasks_from: create_tr_success_fail_doc.yml

    - name: success/Failure logs
      ansible.builtin.import_role:
        name: deco_logging_rack
        tasks_from: add_info_success_fail_doc.yml