---
    - name: Initiating the server info fetch  module task
      throttle: 1
      block:

        - set_fact:
            file_server_info_success: "server_info_success.yml"
            file_server_info_failure: "server_info_failure.yml"             
   
        - name: Display the JSON file content
          shell: cat record_for_server_info_gather.json
          delegate_to: localhost
          register: TR_result_server_info_gather 

        - name: save the Json data to a Variable as a Fact
          set_fact:
            record_id_server_info_gather: "{{ TR_result_server_info_gather.stdout[1:-1] }}"
          delegate_to: localhost         

        - meta: end_host
          when: record_id_server_info_gather == "" 

        - name: Display the JSON file content
          shell: cat private_endpoint_connection_string.yml
          delegate_to: localhost
          register: result_private_endpoint_connection_string
    
        - name: save the Json data to a Variable as a Fact
          set_fact:
            private_endpoint_connection_string: "{{ result_private_endpoint_connection_string.stdout }}"
          delegate_to: localhost
      
        - name: "Check entry for DECO server"
          azure_update_ref_esxi:
            connection_string: "{{ private_endpoint_connection_string }}"
            hostname: "{{inventory_hostname}}"
          register: idem_status 
          delegate_to: localhost

        # - set_fact: 
        #     remote_username: 'root' 

        - set_fact: 
            remote_username: "{{ remote_username }}"

        # - set_fact: 
        #     remote_keyfile: 'N1Flheim!' 
        
        - set_fact: 
            remote_keyfile: "{{ remote_password }}"
                 
        - set_fact: 
            server_info: '{{idem_status.module_update.server_info}}'                  

        - set_fact: 
            esxi_type: '{{idem_status.module_update.esxi_type}}'

        - set_fact: 
            fqdn_info: '{{idem_status.module_update.fqdn_info}}'

        - set_fact: 
            cmdb_fetch: '{{idem_status.module_update.cmdb_fetch}}'    

        - set_fact: 
            vcenter_info: '{{idem_status.module_update.vcenter_info}}'    

        - name: End play for this host
          meta: end_host
          when: vcenter_info == "F" or fqdn_info == "F" or esxi_type == "F" or server_info != "F" or cmdb_fetch == "F"

        - name: "Check entry for DECO server and fetch wwpn information of host"
          storage_state_value_fetch_esxi:
            connection_string: "{{ private_endpoint_connection_string }}"
            hostname: "{{inventory_hostname}}"                        
          register: info_result_host
          delegate_to: localhost 
          when: server_info == "F" and esxi_type != "F" and fqdn_info != "F" and vcenter_info != "F"

############### Gather wwpn, fqdn, ip and os_name information from ESXi server to update storage table ######################
        - name: "ESXi server information gathering"
          gather_host_info_esxi:
            hostname: '{{ fqdn_info }}'
            username: "{{ remote_username }}"
            password: "{{ remote_keyfile }}"                            
          delegate_to: localhost
          register: output_gather_info

        - debug:
            var: output_gather_info        

        - name: Get timestamp from the system
          shell: "date +%Y-%m-%d/%H:%M"
          delegate_to: localhost
          register: tstamp              
                  
        - set_fact:
            time: "{{tstamp.stdout}}"

        - name: "Failure information to file for exception scenario"
          shell: echo "{{ inventory_hostname }}, {{ time }}, [ERROR], {{ output_gather_info.host_result }} " >> {{file_server_info_failure}}                    
          delegate_to: localhost
          when: '"ERROR" in output_gather_info.host_result'

        - meta: end_host
          when: '"ERROR" in output_gather_info.host_result' 

        - set_fact:
            wwpn_host: "{{output_gather_info.host_result.WWPN}}"
          when: output_gather_info.host_result.WWPN is defined 


        - set_fact:  
            fqdn_host: "{{output_gather_info.host_result.fqdn}}"
          when: output_gather_info.host_result.fqdn is defined 

        - set_fact:  
            ip_host: "{{output_gather_info.host_result.ip}}"
          when: output_gather_info.host_result.ip is defined

        - name: "Failure information to file for NA in any of the output scenario"
          shell: echo "{{ inventory_hostname }}, {{ time }}, [ERROR], Issue fetching server info " >> {{ file_server_info_failure }}
          delegate_to: localhost
          when: 
            - (fqdn_host | default('NA')) == "NA"
              or (ip_host | default('NA')) == "NA"

        - meta: end_host
          when:
            - (fqdn_host | default('NA')) == "NA"
              or (ip_host | default('NA')) == "NA"

        - name: Fetch ESXi details
          enclosure_synergon_data_fetch:
            enclosure: "{{ inventory_hostname }}"
            synergon_api: "{{ synergon_url }}"
          delegate_to: localhost
          register: esxi_data

        - name: Set fact for ESXi cluster
          set_fact:
            esxi_cluster: "{{ esxi_data.esxi_details[0].cluster }}"

##################################### Combine ESXi details into a single dictionary ##########################################
        - name: Combine and clean ESXi details into a single dictionary
          set_fact:
            combined_host_info:
              os_name: "{{ output_gather_info.host_result.os_name }}"
              WWPN: "{{ output_gather_info.host_result.WWPN }}"
              fqdn: "{{ output_gather_info.host_result.fqdn }}"
              ip: "{{ output_gather_info.host_result.ip | regex_replace('-------------\\n', '') | trim }}"
              cluster: "{{ esxi_cluster }}"
################################### updating host information -> wwpn, fqdn, ip, os_name in storage table #####################################
        - name: "update storage cleanup state file for DECO server"
          storage_state_values_update_esxi:
            connection_string: "{{ private_endpoint_connection_string }}"
            hostname: "{{ inventory_hostname }}"
            module_name: "host_info"
            status: "{{ output_gather_info.host_result }}"               
          register: update_status_info_gather_fetch
          delegate_to: localhost
          when: wwpn_host != "NA" or fqdn_host != "NA" or ip_host != "NA" or os_host != "NA"                                      

        - set_fact:
             check_update_flag_server: "{{ update_status_info_gather_fetch.module_update }}"
          when: update_status_info_gather_fetch.module_update is defined      
    

        - name: "collecting failure info to failure file"
          shell: echo "{{ inventory_hostname }}, {{ time }}, [ERROR], Unable to update the information to state file.{{ check_update_flag_server }}" >> {{file_server_info_failure}}                    
          delegate_to: localhost 
          when: check_update_flag_server is defined and check_update_flag_server is not search("successfully")

        - meta: end_host
          when: check_update_flag_server is defined and check_update_flag_server is not search("successfully")

        - name: "collecting success info to success file"
          shell: echo "{{ inventory_hostname }}, {{ time }}, [INFO], Successfully fetched server information and updated to state file.{{ output_gather_info.host_result| to_yaml }}" >> {{file_server_info_success}}                    
          delegate_to: localhost 
          when: check_update_flag_server is defined and check_update_flag_server is search("successfully")

################################### Update idempotency state file for server info fetch #####################################
        - name: "update entry for DECO server for server info fetch"
          azure_update_module_vals_esxi:
            connection_string: "{{ private_endpoint_connection_string }}"
            hostname: "{{inventory_hostname}}"
            module_name: "server_info"
            status: "T"          
          register: update_status_info_state
          delegate_to: localhost
          when: check_update_flag_server is defined and check_update_flag_server is search("successfully")

        - set_fact:
             check_state_flag_server: "{{ update_status_info_state.state_update }}"
          when: update_status_info_state.state_update is defined 

        - name: "collecting failure info of state file updation "
          shell: echo "{{ inventory_hostname }}, {{ time }}, [ERROR], Unable to update state file as TRUE.{{ check_state_flag_server }}" >> {{file_server_info_failure}}                    
          delegate_to: localhost 
          when: check_state_flag_server is defined and check_state_flag_server is not search("successfully")         

      rescue: 
        - name: when above one throws error the below task should execute
          debug:
            msg: "Exception occurred but rescued - check errors for server info fetch module"  

        - name: Get timestamp from the system
          shell: "date +%Y-%m-%d/%H:%M"
          delegate_to: localhost
          register: tstamp              
                  
        - set_fact:
            time: "{{tstamp.stdout}}"

        - name: "Failure information to file in rescue block"
          shell: echo "{{ inventory_hostname }}, {{ time }}, [ERROR], Kindly check server info fetch module for esxi servers" >> {{file_server_info_failure}}                    
          delegate_to: localhost
