---
# - name: "This playbook is to add healthcheck info in TR"
#   hosts: localhost
#   gather_facts: no  
#   vars:
#     graceperiod_flag: False

        
#   tasks:      
      ####Adding Info to TR  
    - name: "Handling TR record_id"
      block:

        - name: Display the JSON file content
          shell: cat record_healthcheck_ssh.json
          delegate_to: localhost
          register: TR_result_healthcheck  

        - name: save the Json data to a Variable as a Fact
          set_fact:
            record_healthcheck_ssh: "{{ TR_result_healthcheck.stdout[1:-1] }}"
          delegate_to: localhost

        - meta: end_host
          when: record_healthcheck_ssh == "" 
             

        - name: Display the JSON file content
          shell: cat esxi_ssh_fail.yml
          delegate_to: localhost
          register: result_check_esxi

        - name: save the Json data to a Variable as a Fact
          set_fact:
            esxi_ssh_fail: "{{ result_check_esxi.stdout }}" 
          delegate_to: localhost

        - name: "adding up the healthcheck issue"
          shell: echo "{{ esxi_ssh_fail }}" >> check_final_ssh.yml                    
          delegate_to: localhost            
          when: esxi_ssh_fail != ""            



        - name: Display the JSON file content
          shell: cat check_final_ssh.yml
          delegate_to: localhost
          register: result_check_final

        - name: save the Json data to a Variable as a Fact
          set_fact:
            check_final_ssh: "{{ result_check_final.stdout }}" 
          delegate_to: localhost                                                                                          

        - meta: end_host
          when: check_final_ssh == ""
        
        - set_fact:
            form1: "***********************************************************************"
            form2: "Below are the list of ESXi unable to SSH"
            form3: "***********************************************************************"            
        - set_fact:
            content_check_final_ssh: "{{ form1 +'\n'+ form2 +'\n'+ form3 +'\n'+ check_final_ssh }}"
          when: check_final_ssh != ""  
          

      rescue:
        - debug:
            var: 'check_final_ssh'

    - name: "Handling add message in TR"
      block: 

        - name: ESXI_host list
          shell: cat check_final_ssh.yml
          delegate_to: localhost
          register: ESXI_result              

        - name: save the ESXI list to a Variable as a Fact
          set_fact:
            ESXI_check_final_ssh: "{{ ESXI_result.stdout }}" 
          delegate_to: localhost     

        - meta: end_host
          when: ESXI_check_final_ssh == ""

        - name: Display the JSON file content
          shell: cat record_healthcheck_ssh.json
          delegate_to: localhost
          register: TR_result_healthcheck  

        - name: save the Json data to a Variable as a Fact
          set_fact:
            record_healthcheck_ssh: "{{ TR_result_healthcheck.stdout[1:-1] }}"
          delegate_to: localhost

        - meta: end_host
          when: record_healthcheck_ssh == ""              
     
       
        - name: "Add message to TR"
          add_message_to_tr:
            record_id: "{{ record_healthcheck_ssh }}"
            message: "{{ content_check_final_ssh }}"             
            username: "DecoP112686"     
            password: "opFCtCpIMzmC" 
          delegate_to: localhost
          register: add_msg_output
                                   

      rescue:
        - debug:
            var: 'add_msg_output'

    - name: "Close TR"
      block:  
        
        - name: ESXI_host list
          shell: cat record_healthcheck_ssh.json
          delegate_to: localhost
          register: ESXI_result             

        - name: save the ESXI list to a Variable as a Fact
          set_fact:
            record_healthcheck_ssh: "{{ ESXI_result.stdout[1:-1] }}"  
          delegate_to: localhost


        - name: "Test custome module [CLOSE TR]"
          close_tr:
            record_id: "{{ record_healthcheck_ssh }}"
            username: "DecoP112686"
            password: "opFCtCpIMzmC"
          register: close_tr_output
                               

      rescue:
        - debug:
            var: close_tr_output         


            
        
            
             