---
    - name: "Handling TR record_id"
      block:

        - name: Display the JSON file content
          shell: cat record_healthcheck.json
          delegate_to: localhost
          register: TR_result_healthcheck  

        - name: save the Json data to a Variable as a Fact
          set_fact:
            record_id_healthcheck: "{{ TR_result_healthcheck.stdout[1:-1] }}"
          delegate_to: localhost

        - meta: end_host
          when: record_id_healthcheck == ""   


        # - name: Display the JSON file content
        #   shell: cat check_artifacts_success.yml
        #   delegate_to: localhost
        #   register: result_check_arti_suc

        # - name: save the Json data to a Variable as a Fact
        #   set_fact:
        #     check_artifacts_success: "{{ result_check_arti_suc.stdout }}" 
        #   delegate_to: localhost 

        # - name: "adding up the healthcheck issue"
        #   shell: echo "{{ check_artifacts_success }}" >> check_final_success.yml                    
        #   delegate_to: localhost            
        #   when: check_artifacts_success != ""     
      
        - name: Display the JSON file content
          shell: cat check_synergon_success.yml
          delegate_to: localhost
          register: result_check_syner_success

        - name: save the Json data to a Variable as a Fact
          set_fact:
            check_synergon_success: "{{ result_check_syner_success.stdout }}" 
          delegate_to: localhost

        - name: "adding up the healthcheck issue"
          shell: echo "{{ check_synergon_success }}" >> check_final_success.yml                    
          delegate_to: localhost            
          when: check_synergon_success != ""          

        - name: Display the JSON file content
          shell: cat check_remedy_success.yml
          delegate_to: localhost
          register: result_check_remedy_succ

        - name: save the Json data to a Variable as a Fact
          set_fact:
            check_remedy_success: "{{ result_check_remedy_succ.stdout }}" 
          delegate_to: localhost

        - name: "adding up the healthcheck issue"
          shell: echo "{{ check_remedy_success }}" >> check_final_success.yml                    
          delegate_to: localhost            
          when: check_remedy_success != ""            

        - name: Display the JSON file content
          shell: cat check_vcenter_success.yml
          delegate_to: localhost
          register: result_check_vcenter_succ

        - name: save the Json data to a Variable as a Fact
          set_fact:
            check_vcenter_success: "{{ result_check_vcenter_succ.stdout }}" 
          delegate_to: localhost 

        - name: "adding up the healthcheck issue"
          shell: echo "{{ check_vcenter_success }}" >> check_final_success.yml                    
          delegate_to: localhost            
          when: check_vcenter_success != "" 

        - name: Display the JSON file content
          shell: cat check_ssh_linux_success.yml
          delegate_to: localhost
          register: result_check_ssh_linux_success

        - name: save the Json data to a Variable as a Fact
          set_fact:
            check_ssh_linux_success: "{{ result_check_ssh_linux_success.stdout }}" 
          delegate_to: localhost 

        - name: "adding up the healthcheck issue"
          shell: echo "{{ check_ssh_linux_success }}" >> check_final_success.yml                    
          delegate_to: localhost            
          when: check_ssh_linux_success != ""

        - name: Display the JSON file content
          shell: cat check_ssh_windows_success.yml
          delegate_to: localhost
          register: result_check_ssh_windows_succ

        - name: save the Json data to a Variable as a Fact
          set_fact:
            check_ssh_windows_success: "{{ result_check_ssh_windows_succ.stdout }}" 
          delegate_to: localhost 

        - name: "adding up the healthcheck issue"
          shell: echo "{{ check_ssh_windows_success }}" >> check_final_success.yml                    
          delegate_to: localhost            
          when: check_ssh_windows_success != ""                             


        - name: Display the JSON file content
          shell: cat check_final_success.yml
          delegate_to: localhost
          register: result_check_final_suc

        - name: save the Json data to a Variable as a Fact
          set_fact:
            check_final_success: "{{ result_check_final_suc.stdout }}" 
          delegate_to: localhost                                                                                          

        
        - set_fact:
            form1: "***********************************************************************"
            form2: "Below are the DECO results for API checks - VMs"
            form3: "***********************************************************************"            
        - set_fact:
            content_check_final_suc: "{{ form1 +'\n'+ form2 +'\n'+ form3 +'\n'+ check_final_success }}"
          when: check_final_success != ""  
          

      rescue:
        - debug:
            var: 'check_final_success'

    - name: "Handling add message in TR"
      block: 

        - name: VM_host list
          shell: cat check_final_success.yml
          delegate_to: localhost
          register: vm_result              

        - name: save the vm list to a Variable as a Fact
          set_fact:
            vm_check_final_suc: "{{ vm_result.stdout }}" 
          delegate_to: localhost     


        - name: Display the JSON file content
          shell: cat record_healthcheck.json
          delegate_to: localhost
          register: TR_result_healthcheck  

        - name: save the Json data to a Variable as a Fact
          set_fact:
            record_id_healthcheck: "{{ TR_result_healthcheck.stdout[1:-1] }}"
          delegate_to: localhost

        - meta: end_host
          when: record_id_healthcheck == ""              
     
       
        - name: "Add message to TR"
          add_message_to_tr:
            record_id: "{{ record_id_healthcheck }}"
            message: "{{ content_check_final_suc }}"             
            username: "{{ winaproach_username }}"     
            password: "{{ winaproach_password }}" 
          delegate_to: localhost
          register: add_msg_output
          when: vm_check_final_suc != ""                                   

      rescue:
        - debug:
            var: 'add_msg_output'



    - name: "Handling TR record_id"
      block:

        - name: Display the JSON file content
          shell: cat record_healthcheck.json
          delegate_to: localhost
          register: TR_result_healthcheck  

        - name: save the Json data to a Variable as a Fact
          set_fact:
            record_id_healthcheck: "{{ TR_result_healthcheck.stdout[1:-1] }}"
          delegate_to: localhost

        - meta: end_host
          when: record_id_healthcheck == ""   


        # - name: Display the JSON file content
        #   shell: cat check_artifacts.yml
        #   delegate_to: localhost
        #   register: result_check_arti

        # - name: save the Json data to a Variable as a Fact
        #   set_fact:
        #     check_artifacts: "{{ result_check_arti.stdout }}" 
        #   delegate_to: localhost

        # - name: "adding up the healthcheck issue"
        #   shell: echo "{{ check_artifacts }}" >> check_final.yml                    
        #   delegate_to: localhost            
        #   when: check_artifacts != ""      
    
       

        - name: Display the JSON file content
          shell: cat check_remedy.yml
          delegate_to: localhost
          register: result_check_remedy

        - name: save the Json data to a Variable as a Fact
          set_fact:
            check_remedy: "{{ result_check_remedy.stdout }}" 
          delegate_to: localhost

        - name: "adding up the healthcheck issue"
          shell: echo "{{ check_remedy }}" >> check_final.yml                    
          delegate_to: localhost            
          when: check_remedy != ""          

        - name: Display the JSON file content
          shell: cat check_synergon.yml
          delegate_to: localhost
          register: result_check_synergon

        - name: save the Json data to a Variable as a Fact
          set_fact:
            check_synergon: "{{ result_check_synergon.stdout }}" 
          delegate_to: localhost

        - name: "adding up the healthcheck issue"
          shell: echo "{{ check_synergon }}" >> check_final.yml                    
          delegate_to: localhost            
          when: check_synergon != ""            

        - name: Display the JSON file content
          shell: cat check_vcenter.yml
          delegate_to: localhost
          register: result_check_vcenter

        - name: save the Json data to a Variable as a Fact
          set_fact:
            check_vcenter: "{{ result_check_vcenter.stdout }}" 
          delegate_to: localhost

        - name: "adding up the healthcheck issue"
          shell: echo "{{ check_vcenter }}" >> check_final.yml                    
          delegate_to: localhost            
          when: check_vcenter != ""          


        - name: Display the JSON file content
          shell: cat check_final.yml
          delegate_to: localhost
          register: result_check_final

        - name: save the Json data to a Variable as a Fact
          set_fact:
            check_final: "{{ result_check_final.stdout }}" 
          delegate_to: localhost                                                                                        


        
        - set_fact:
            form1: "***********************************************************************"
            form2: "Below are the DECO results for API checks - VMs"
            form3: "***********************************************************************"            
        - set_fact:
            content_check_final: "{{ form1 +'\n'+ form2 +'\n'+ form3 +'\n'+ check_final }}"
          when: check_final != ""  
          

      rescue:
        - debug:
            var: 'check_final'

    - name: "Handling add message in TR"
      block: 

        - name: VM_host list
          shell: cat check_final.yml
          delegate_to: localhost
          register: vm_result              

        - name: save the vm list to a Variable as a Fact
          set_fact:
            vm_check_final: "{{ vm_result.stdout }}" 
          delegate_to: localhost     

        - name: Display the JSON file content
          shell: cat record_healthcheck.json
          delegate_to: localhost
          register: TR_result_healthcheck  

        - name: save the Json data to a Variable as a Fact
          set_fact:
            record_id_healthcheck: "{{ TR_result_healthcheck.stdout[1:-1] }}"
          delegate_to: localhost

        - meta: end_host
          when: record_id_healthcheck == ""              
     
       
        - name: "Add message to TR"
          add_message_to_tr:
            record_id: "{{ record_id_healthcheck }}"
            message: "{{ content_check_final }}"             
            username: "{{ winaproach_username }}"     
            password: "{{ winaproach_password }}" 
          delegate_to: localhost
          register: add_msg_output
          when: vm_check_final != ""
                                   

      rescue:
        - debug:
            var: 'add_msg_output'

    - name: "Close TR"
      block:  
        
        - name: VM_host list
          shell: cat record_healthcheck.json
          delegate_to: localhost
          register: vm_result             

        - name: save the vm list to a Variable as a Fact
          set_fact:
            record_id_healthcheck: "{{ vm_result.stdout[1:-1] }}"  
          delegate_to: localhost


        - name: "Test custome module [CLOSE TR]"
          close_tr:
            record_id: "{{ record_id_healthcheck }}"
            username: "{{ winaproach_username }}"
            password: "{{ winaproach_password }}"
          register: close_tr_output
                               

      rescue:
        - debug:
            var: close_tr_output         


            
        
            
             