---
    # - name: "Deco Health check status"
    #   block:

    #     - name: Display the JSON file content
    #       shell: cat state_file.yml
    #       delegate_to: localhost
    #       register: result_state_file

    #     - name: save the Json data to a Variable as a Fact
    #       set_fact:
    #         state_file: "{{ result_state_file.stdout }}" 
    #       delegate_to: localhost


    #     - name: Check if artifact api up or not
    #       uri:
    #         url: https://{{ state_file }}
    #       register: result_artifacts
    #       until: "result_artifacts.status == 200"
    #       retries: 3
    #       delay: 10


    #     - name: Get timestamp from the system
    #       shell: "date +%Y-%m-%d/%H:%M"
    #       delegate_to: localhost
    #       register: tstamp  
                      
    #     - set_fact:
    #         time: "{{tstamp.stdout}}"             

    #     - name: "artifact repo status"
    #       shell: echo "#Artifacts repo - {{ time }}, [INFO], {{ state_file }} is up and running, good to proceed with VM deco trigger 1" >> check_artifacts_success.yml   
    #       delegate_to: localhost                    

    #   rescue:
    #     - debug:
    #         msg: "artifact repo unavaiable"

    #     - name: Get timestamp from the system
    #       shell: "date +%Y-%m-%d/%H:%M"
    #       delegate_to: localhost
    #       register: tstamp  
                      
    #     - set_fact:
    #         time: "{{tstamp.stdout}}"             

    #     - name: "artifact repo status"
    #       shell: echo "!Artifacts repo - {{ time }}, [ERROR], {{ state_file }} is down currently after 3 retries needs attention" >> check_artifacts.yml   
    #       delegate_to: localhost



    - name: "Deco Health check status"
      block:

        - name: Display the JSON file content
          shell: cat synergon_url.yml
          delegate_to: localhost
          register: result_synergon_url

        - name: save the Json data to a Variable as a Fact
          set_fact:
            synergon_url: "{{ result_synergon_url.stdout }}" 
          delegate_to: localhost      

        - name: Check if synergon api up or not
          uri:
            url: https://{{ synergon_url }}/v1/ui#/vm/list_vms_vms__get           
          register: result_synergon
          until: "result_synergon.status == 200"
          retries: 3
          delay: 10

     
        - name: Get timestamp from the system
          shell: "date +%Y-%m-%d/%H:%M"
          delegate_to: localhost
          register: tstamp  
                      
        - set_fact:
            time: "{{tstamp.stdout}}"            

        - name: "Synergon status"
          shell: echo "#Synergon api - {{ time }}, [INFO], {{ synergon_url }} is up and running, good to proceed with VM deco trigger 1" >> check_synergon_success.yml   
          delegate_to: localhost          


      rescue:
        - debug:
            msg: "Synergon is unavaiable" 

        - name: Get timestamp from the system
          shell: "date +%Y-%m-%d/%H:%M"
          delegate_to: localhost
          register: tstamp  
                      
        - set_fact:
            time: "{{tstamp.stdout}}"            

        - name: "Synergon status"
          shell: echo "!Synergon api - {{ time }}, [ERROR], {{ synergon_url }} is down currently after 3 retries needs attention" >> check_synergon.yml   
          delegate_to: localhost


    - name: "Deco Health check status"
      block:

        - name: Display the JSON file content
          shell: cat cmdb_url_update.yml
          delegate_to: localhost
          register: result_cmdb_url_update

        - name: save the Json data to a Variable as a Fact
          set_fact:
            cmdb_url_update: "{{ result_cmdb_url_update.stdout }}" 
          delegate_to: localhost      

        - name: Check if remedy api up or not
          uri:
            url: "{{ cmdb_url_update }}/api/arsys/v1/entry" # http://{{ cmdb_url_update }}:8008/api/arsys/v1/entry
          register: result_remedy
          until: "result_remedy.status == 200"
          retries: 3
          delay: 10
          when: cmdb_url_update is search("{{CMDB_URL}}")  

        - name: Get timestamp from the system
          shell: "date +%Y-%m-%d/%H:%M"
          delegate_to: localhost
          register: tstamp
          when: cmdb_url_update is search("{{CMDB_URL}}")   
                      
        - set_fact:
            time: "{{tstamp.stdout}}"
          when: cmdb_url_update is search("{{CMDB_URL}}")               

        - name: "Remedy status"
          shell: echo "#Remedy - {{ time }}, [INFO], {{ cmdb_url_update }} is up and running, good to proceed with VM deco trigger 1" >> check_remedy_success.yml   
          delegate_to: localhost
          when: cmdb_url_update is search("{{CMDB_URL}}")           


      rescue:
        - debug:
            msg: "Remedy is unavaiable to update CMDB"

        - name: Get timestamp from the system
          shell: "date +%Y-%m-%d/%H:%M"
          delegate_to: localhost
          register: tstamp 
          when: cmdb_url_update is search("{{CMDB_URL}}")   
                      
        - set_fact:
            time: "{{tstamp.stdout}}"
          when: cmdb_url_update is search("{{CMDB_URL}}")                

        - name: "Remedy status"
          shell: echo "!Remedy - {{ time }}, [ERROR], {{ cmdb_url_update }} is down currently after 3 retries needs attention" >> check_remedy.yml   
          delegate_to: localhost
          when: cmdb_url_update is search("{{CMDB_URL}}")  

    - name: "Deco Health check status"
      block:

        - name: Display the JSON file content
          shell: cat cmdb_url_update.yml
          delegate_to: localhost
          register: result_cmdb_url_update

        - name: save the Json data to a Variable as a Fact
          set_fact:
            cmdb_url_update: "{{ result_cmdb_url_update.stdout }}" 
          delegate_to: localhost      

        - name: Check if remedy api up or not
          uri:
            url: "{{ cmdb_url_update }}/api/arsys/v1/entry" # http://{{ cmdb_url_update }}:8008/api/arsys/v1/entry
          register: result_remedy
          until: "result_remedy.status == 200"
          retries: 3
          delay: 10
          when: cmdb_url_update is search("{{CMDB_URL}}") 

        - name: Get timestamp from the system
          shell: "date +%Y-%m-%d/%H:%M"
          delegate_to: localhost
          register: tstamp
          when: cmdb_url_update is search("{{CMDB_URL}}")  
                      
        - set_fact:
            time: "{{tstamp.stdout}}"
          when: cmdb_url_update is search("{{CMDB_URL}}")              

        - name: "Remedy status"
          shell: echo "#Remedy - {{ time }}, [INFO], {{ cmdb_url_update }} is up and running, good to proceed with VM deco trigger 1" >> check_remedy_success.yml   
          delegate_to: localhost
          when: cmdb_url_update is search("{{CMDB_URL}}")          


      rescue:
        - debug:
            msg: "Remedy is unavaiable to update CMDB"

        - name: Get timestamp from the system
          shell: "date +%Y-%m-%d/%H:%M"
          delegate_to: localhost
          register: tstamp
          when: cmdb_url_update is search("{{CMDB_URL}}")   
                      
        - set_fact:
            time: "{{tstamp.stdout}}"
          when: cmdb_url_update is search("{{CMDB_URL}}")             

        - name: "Remedy status"
          shell: echo "!Remedy - {{ time }}, [ERROR], {{ cmdb_url_update }} is down currently after 3 retries needs attention" >> check_remedy.yml   
          delegate_to: localhost
          when: cmdb_url_update is search("{{CMDB_URL}}")           
            
                    
