- name: "Host Method - Storage Controller Cleanup"
  throttle: 1
  vars:
      private_volumes: []
      all_volume_unmap: ""
      server_deletion_result: ""
      rename_hostmethod_output: "success"
  block:

    - name: Display the JSON file content for storage cleanup  
      shell: cat record_storage_cleanup_phy.json
      delegate_to: localhost
      register: TR_result_storage_cleanup  

    - name: save the Json data to a Variable as a Fact for storage cleanup
      set_fact:
        record_id_storage_cleanup: "{{ TR_result_storage_cleanup.stdout[1:-1] }}"
      delegate_to: localhost

    - set_fact:
        volume_err: ""
    - set_fact:
        private_volumes: ""
    - set_fact:
        uid_volumes: ""       
    - set_fact:
        uid_scsi: ""                
         
    - name: "Check private volume mappings for the Host"
      ibm.spectrum_virtualize.ibm_svcinfo_command:
        command: "svcinfo lshostvdiskmap {{ inventory_hostname }}" 
        clustername: "{{ storage_sys }}"
        username: "{{ synergon_username }}"
        password: "{{ synergon_password }}"
      register: privatevolumedata
      delegate_to: localhost
      ignore_errors: True

    - name: "Debug private volume mappings output"
      debug:
        var: privatevolumedata.stdout

    - name: "private volume mappings"
      check_private_volumedata:
        privatevolume_data: "{{ privatevolumedata.stdout }}"
      register: volumes_private
      delegate_to: localhost
      when: privatevolumedata.stdout != ""

    - name: "Debug private volume mappings output"
      debug:
        var: volumes_private

    - set_fact:
        private_volumes: "{{ volumes_private.data }}"
      delegate_to: localhost
      when: privatevolumedata.stdout != ""

    - set_fact:
        uid_volumes: "{{ volumes_private.uid }}"
      delegate_to: localhost
      when: privatevolumedata.stdout != "" 

    - set_fact:
        uid_scsi: "{{ volumes_private.scsi }}"
      delegate_to: localhost
      when: privatevolumedata.stdout != ""   

    - name: populate combined var
      set_fact:
        combined_var: "{{ combined_var|default([]) + [dict(uid=inner_item[0], volume=inner_item[1],scsi=inner_item[2])] }}"
      loop: "{{ uid_volumes | zip_longest(private_volumes,uid_scsi) | list }}"
      loop_control:
        loop_var: inner_item
      register: combined_var
      delegate_to: localhost
      when: private_volumes | length != 0

    - set_fact:
        last_in_list: "{{ combined_var.results |last }}"
      delegate_to: localhost
      when: private_volumes | length != 0  

    - set_fact:
        vol_uid: "{{ last_in_list.ansible_facts.combined_var | to_json}}"
      delegate_to: localhost     
      when: private_volumes | length != 0  

    - name: "Physical host list"
      shell: echo "{{ inventory_hostname }} - Host_private_mapped_volumes - {{vol_uid}}." >> {{file_info_storage}}                   
      delegate_to: localhost
      when: private_volumes | length != 0

    - name: "Physical host list"
      shell: echo "{{ inventory_hostname }} - Host_private_mapped_volumes - No Private volumes mapped to the Host." >> {{file_info_storage}}                   
      delegate_to: localhost
      when: private_volumes | length == 0

    - name: "Check if private volumes are not empty"
      set_fact:
        has_private_volumes: "{{ private_volumes | length > 0 }}"

    - name: "Unmapping the private volumes from the host"
      ibm.spectrum_virtualize.ibm_svc_vol_map:
        clustername: "{{ storage_sys }}" 
        host: "{{ inventory_hostname }}"
        username: "{{ synergon_username }}"
        password: "{{ synergon_password }}"
        volname: "{{ inner_item }}" 
        state: absent
      loop: "{{ private_volumes }}"
      loop_control:
        loop_var: inner_item
      register: unmap_output
      delegate_to: localhost
      when: has_private_volumes
      ignore_unreachable: true

    - set_fact:
        volume_err: "{{ unmap_output.results | lower }}"
      delegate_to: localhost
      when: has_private_volumes 

    - name: Get timestamp from the system
      shell: "date +%Y-%m-%d/%H:%M"
      delegate_to: localhost
      register: tstamp
    - set_fact:
          time: "{{tstamp.stdout}}"

    - name: "Physical host list"
      shell: echo "{{ inventory_hostname }}, {{ time }}, [INFO], {{ storage_sys }} - Volume protection enabled hence unable to unmap volume" >> {{file_storage_cleanup_suc}}                    
      delegate_to: localhost
      when: volume_err is search("failed to obtain access token")

    - name: "Physical host list"
      shell: echo "{{ inventory_hostname }}, {{ time }}, [INFO], {{ storage_sys }} - Volume protection enabled hence unable to unmap volume" >> {{file_storage_cleanup_suc_vol}}                    
      delegate_to: localhost
      when: volume_err is search("failed to obtain access token")      

    - meta: end_host
      when: volume_err is search("failed to obtain access token") 

    - name: "Debug Unmapping the private volumes output"
      debug:
        var: unmap_output

    - name: "private volume unmap output"
      check_private_unmapped_data:
        unmap_data: "{{ unmap_output.results }}"
      register: private_unmap_output
      delegate_to: localhost
      when: private_volumes | length != 0

    - name: "Debug private volume unmap output"
      debug:
        var: private_unmap_output

    - name: "Delete a server (Host Entry)"
      ibm.spectrum_virtualize.ibm_svc_host:
        clustername: "{{ storage_sys }}" 
        username: "{{ synergon_username }}"
        password: "{{ synergon_password }}"
        name: "{{ inventory_hostname }}"
        state: absent
      register: server_deletion_output
      delegate_to: localhost

    - name: "Debug Delete a server (Host Entry) output"
      debug:
        var: server_deletion_output

    - set_fact:
          server_deletion_result: "{{server_deletion_output.msg}}"
      delegate_to: localhost

    - name: Get timestamp from the system
      shell: "date +%Y-%m-%d/%H:%M"
      delegate_to: localhost
      register: tstamp  
    
    - set_fact:
          time: "{{tstamp.stdout}}"

    - name: "Write Failure host to file"
      shell: echo "{{ inventory_hostname }} Failure" >> phy_storage_cleanup_failure.txt                  
      delegate_to: localhost
      when: '"deleted" not in server_deletion_result'

    - name: "Physical host list"
      shell: echo "{{ inventory_hostname }}, {{ time }}, [ERROR], {{ storage_sys }} -Server Not Deleted. Check errors in hostmethod module." >> {{file_storage_cleanup_fail}}                    
      delegate_to: localhost   
      when: '"deleted" not in server_deletion_result'
    
    - meta: end_host
      when: '"deleted" not in server_deletion_result'

    - name: "Check if unmapped volume is mapped to other hosts."
      ibm.spectrum_virtualize.ibm_svcinfo_command:
        command: "svcinfo lsvdiskhostmap {{ inner_item }}"
        clustername: "{{ storage_sys }}"
        username: "{{ synergon_username }}"
        password: "{{ synergon_password }}"
      loop: "{{ private_volumes }}"
      loop_control:
        loop_var: inner_item
      register: vdiskhostmapoutput
      delegate_to: localhost
      when: private_volumes | length != 0

    - name: "Debug lsvdiskhostmap output"
      debug:
        var: vdiskhostmapoutput

    - name: "Parse vdiskhostmapoutput"
      check_volumes_torename:
        lsvdisk_output: "{{ vdiskhostmapoutput.results }}"
      register: vdisklist
      delegate_to: localhost
      when: private_volumes | length != 0

    - name: "Debug parse_lsvdiskhostmap_output"
      debug:
        var: vdisklist

    - name: "Filter out volumes that have to be renamed"
      filter_vols_for_renaming:
        vols: "{{ vdisklist.data }}" 
        TR: "{{ record_id_storage_cleanup }}" #"{{ input.TR }}"
      register: vols_to_be_renamed 
      delegate_to: localhost
      when: private_volumes | length != 0

    - name: "Debug list of volumes to be renamed"
      debug:
        var: vols_to_be_renamed

    - name: "Rename host private mapped volume"
      ibm.spectrum_virtualize.ibm_svctask_command:
        command: ["svctask chvdisk -name {{inner_item.newname}} {{inner_item.oldname}}"]
        clustername: "{{ storage_sys }}"
        username: "{{ synergon_username }}"
        password: "{{ synergon_password }}"
      loop: "{{vols_to_be_renamed.vols}}"
      loop_control:
        loop_var: inner_item
      register: renamevolumeoutput
      delegate_to: localhost
      when: private_volumes | length != 0

    - name: "Debug Rename host private mapped volume output"
      debug:
        var: renamevolumeoutput

    - name: "Rename output"
      check_rename_output:
        rename_output: "{{ renamevolumeoutput.results }}"
      delegate_to: localhost
      register: output_rename
      when: private_volumes | length != 0

    - name: "Debug Rename output"
      debug:
        var: output_rename

    - set_fact:
          rename_hostmethod_output: "{{output_rename.data}}"
      delegate_to: localhost
      when: private_volumes | length != 0

    - name: Get timestamp from the system
      shell: "date +%Y-%m-%d/%H:%M"
      delegate_to: localhost
      register: tstamp  
    - set_fact:
          time: "{{tstamp.stdout}}"

    - name: "Write Failure host to file"
      shell: echo "{{ inventory_hostname }} Failure" >> phy_storage_cleanup_failure.txt                  
      delegate_to: localhost
      when: rename_hostmethod_output == "fails"
          
    - name: "Physical host list"
      shell: echo "{{ inventory_hostname }}, {{ time }}, [ERROR], {{ storage_sys }}- Unmapped volumes are not renamed. Check errors in hostmethod module." >> {{file_storage_cleanup_fail}}                    
      delegate_to: localhost   
      when: rename_hostmethod_output == "fails"
######################SUCCESS UPDATE TO TR#########################    
    - name: "Physical host list - success update"
      shell: echo "{{ inventory_hostname }}, {{ time }}, [INFO], {{ storage_sys }}-Storage Controller Cleanup has completed successfully." >> {{file_storage_cleanup_suc}}                    
      delegate_to: localhost   
      when: server_deletion_result is search("has been deleted") and rename_hostmethod_output == "success"
########################################################################    
  rescue: 
    - name: When above one throws error the below task should execute
      debug:
        msg: "Exception occurred but rescued - check errors on host method module"  
    
    - name: Get timestamp from the system
      shell: "date +%Y-%m-%d/%H:%M"
      delegate_to: localhost
      register: tstamp  
    
    - set_fact:
          time: "{{tstamp.stdout}}"
    
    - name: "Write Failure host to file"
      shell: echo "{{ inventory_hostname }} Failure" >> phy_storage_cleanup_failure.txt                  
      delegate_to: localhost
      
    - name: "Physical host list"
      shell: echo "{{ inventory_hostname }}, {{ time }}, [ERROR], {{ storage_sys }} - hostmethod module." >> {{file_storage_cleanup_fail}}                    
      delegate_to: localhost   