---
  # tasks: 
    - name: "Handling Create TR- Win@proach for Server info fetch  "
      block: 
        - name: Display the JSON file content
          shell: cat record_healthcheck.json
          delegate_to: localhost
          register: TR_result_healthcheck  

        - name: save the Json data to a Variable as a Fact
          set_fact:
            record_id_healthcheck: "{{ TR_result_healthcheck.stdout[1:-1] }}"
          delegate_to: localhost

        - meta: end_host
          when: record_id_healthcheck != ""          

        - name: Physical_host list
          shell: cat host_list_server_info_gather.yml
          delegate_to: localhost
          register: hostlist_physical             

        - name: save the physical list to a Variable as a Fact
          set_fact:
            physical_hostlist: "{{ hostlist_physical.stdout[:-1] }}" 
          delegate_to: localhost 

        - meta: end_host
          when: physical_hostlist == ""       

        - name: "Custom module [CREATE TR]"
          create_tr:
            record_type: "TR"
            title: "CSTY:DECO:DCAT: PHYSICAL DECO - Server info fetch"
            assignee_name: "DecoP112686"
            assignee_group: "DINFDECO"   #"DINFDECO"            
            severity: "4"
            overview: "PHYSICAL DECO - Server info fetch"
            parent_id: "{{ cr }}"            
            username: "{{ winaproach_username }}"     
            password: "{{ winaproach_password }}"
          delegate_to: localhost  
          no_log: False
          register: create_tr_output
       
        - set_fact:
            record_server_info_gather: "{{create_tr_output.record_id}}"

        - copy:
            content: '{{ record_server_info_gather|to_json }}'
            dest: record_for_server_info_gather.json
          delegate_to: localhost

        - name: adding documentation tag
          tr_documentation:
            username: "{{ winaproach_username }}"    
            password: "{{ winaproach_password }}"
            win_url: "WIN@PROACH_URL"
            task_id: "{{ record_server_info_gather }}"
          register: add_document
          delegate_to: localhost

      rescue:
        - debug:
            msg: "Failed to Create PHYSICAL DECO - for Server info fetch "

    - name: "Handling Create TR- Win@proach forStorage info fetch- Retry 1"
      block:

        - name: Display the JSON file content
          shell: cat record_healthcheck.json
          delegate_to: localhost
          register: TR_result_healthcheck  

        - name: save the Json data to a Variable as a Fact
          set_fact:
            record_id_healthcheck: "{{ TR_result_healthcheck.stdout[1:-1] }}"
          delegate_to: localhost

        - meta: end_host
          when: record_id_healthcheck != ""      

        - name: physical_host list
          shell: cat host_list_server_info_gather.yml
          delegate_to: localhost
          register: hostlist_physical              

        - name: save the physical list to a Variable as a Fact
          set_fact:
            physical_hostlist: "{{ hostlist_physical.stdout[:-1] }}" 
          delegate_to: localhost 

        - meta: end_host
          when: physical_hostlist == ""

        - name: Display the JSON file content
          shell: cat record_for_server_info_gather.json
          delegate_to: localhost
          register: TR_result
    
        - name: save the Json data to a Variable as a Fact
          set_fact:
            record_for_server_info_gather: "{{ TR_result.stdout[1:-1] }}" 
          delegate_to: localhost          


        - name: Sleep for 20 seconds and continue with play
          ansible.builtin.wait_for:
            timeout: 20
          delegate_to: localhost
          when: record_for_server_info_gather == "" 

        - name: "Custom module [CREATE TR]"
          create_tr:
            record_type: "TR"
            title: "CSTY:DECO:DCAT: PHYSICAL DECO - Server info fetch"
            assignee_name: "DecoP112686"
            assignee_group: "DINFDECO"   #"DINFDECO"            
            severity: "4"
            overview: "PHYSICAL DECO - Server info fetch"
            parent_id: "{{ cr }}"            
            username: "{{ winaproach_username }}"     
            password: "{{ winaproach_password }}"
          delegate_to: localhost  
          no_log: False
          register: create_tr_output
          when: record_for_server_info_gather == "" 

        - set_fact:
            record_server_info_gather: "{{create_tr_output.record_id}}"
          when: record_for_server_info_gather == "" 

        - copy:
            content: '{{ record_server_info_gather|to_json }}'
            dest: record_for_server_info_gather.json
          delegate_to: localhost
          when: record_for_server_info_gather == "" 

        - name: adding documentation tag
          tr_documentation:
            username: "{{ winaproach_username }}"    
            password: "{{ winaproach_password }}"
            win_url: "WIN@PROACH_URL"
            task_id: "{{ record_server_info_gather }}"
          register: add_document
          delegate_to: localhost
          when: record_for_server_info_gather == "" 

      rescue:
        - debug:
            msg: "Retried and Failed to Create PHYSICAL DECO -for Server info fetch TR"

    - name: "Handling Create TR- Win@proach for for Server info fetch -Retry 2 "
      block:

        - name: Display the JSON file content
          shell: cat record_healthcheck.json
          delegate_to: localhost
          register: TR_result_healthcheck  

        - name: save the Json data to a Variable as a Fact
          set_fact:
            record_id_healthcheck: "{{ TR_result_healthcheck.stdout[1:-1] }}"
          delegate_to: localhost

        - meta: end_host
          when: record_id_healthcheck != ""      

        - name: physical_host list
          shell: cat host_list_server_info_gather.yml
          delegate_to: localhost
          register: hostlist_physical              

        - name: save the physical list to a Variable as a Fact
          set_fact:
            physical_hostlist: "{{ hostlist_physical.stdout[:-1] }}" 
          delegate_to: localhost 

        - meta: end_host
          when: physical_hostlist == ""

        - name: Display the JSON file content
          shell: cat record_for_server_info_gather.json
          delegate_to: localhost
          register: TR_result
    
        - name: save the Json data to a Variable as a Fact
          set_fact:
            record_for_server_info_gather: "{{ TR_result.stdout[1:-1] }}" 
          delegate_to: localhost          


        - name: Sleep for 20 seconds and continue with play
          ansible.builtin.wait_for:
            timeout: 20
          delegate_to: localhost
          when: record_for_server_info_gather == "" 

        - name: "Custom module [CREATE TR]"
          create_tr:
            record_type: "TR"
            title: "CSTY:DECO:DCAT: PHYSICAL DECO - Server info fetch"
            assignee_name: "DecoP112686"
            assignee_group: "DINFDECO"   #"DINFDECO"            
            severity: "4"
            overview: "PHYSICAL DECO - Server info fetch"
            parent_id: "{{ cr }}"            
            username: "{{ winaproach_username }}"     
            password: "{{ winaproach_password }}"
          delegate_to: localhost  
          no_log: False
          register: create_tr_output
          when: record_for_server_info_gather == "" 

        - set_fact:
            record_server_info_gather: "{{create_tr_output.record_id}}"
          when: record_for_server_info_gather == "" 

        - copy:
            content: '{{ record_server_info_gather|to_json }}'
            dest: record_for_server_info_gather.json
          delegate_to: localhost
          when: record_for_server_info_gather == "" 

        - name: adding documentation tag
          tr_documentation:
            username: "{{ winaproach_username }}"    
            password: "{{ winaproach_password }}"
            win_url: "WIN@PROACH_URL"
            task_id: "{{ record_server_info_gather }}"
          register: add_document
          delegate_to: localhost
          when: record_for_server_info_gather == "" 
          
      rescue:
        - debug:
            msg: "Retried and Failed to Create PHYSICAL DECO - Server info fetch  TR"                        
