---
    - name: Initiating the CMDB update module task
      throttle: 1
      block:

        - set_fact:
            file_cmdb_fail: "cmdb_failure.yml"
            file_cmdb_suc: "cmdb_success.yml"
            CMDB_RESULT: ""      

        - name: Display the JSON file content for cmdb update
          shell: cat record_cmdb_update_phy.json
          delegate_to: localhost
          register: TR_result_cmdb_up_phy

        - name: save the Json data to a Variable as a Fact for cmdb update
          set_fact:
            record_id_cmdb_up_phy: "{{ TR_result_cmdb_up_phy.stdout[1:-1] }}"
          delegate_to: localhost         

        - meta: end_host
          when: record_id_cmdb_up_phy == ""      

        - name: Display the JSON file content
          shell: cat private_endpoint_connection_string.yml
          delegate_to: localhost
          register: result_private_endpoint_connection_string

        - name: save the Json data to a Variable as a Fact
          set_fact:
            private_endpoint_connection_string: "{{ result_private_endpoint_connection_string.stdout }}"
          delegate_to: localhost

        - name: "change hostname to lower case"
          set_fact:
            cmdb_vmname_new: "{{inventory_hostname |lower }}"               
                          
        - name: "Test custom module for Updating CMDB with CI status after deletion"
          update_cmdb:
            conn_str: "{{ private_endpoint_connection_string }}"
            server_name: '{{cmdb_vmname_new}}'
            instance_id: '{{ instanceid }}'
            cmdb_server: "{{ cmdb_url_update }}"
            user_name: "{{ emdb_username }}"
            pass_word: "{{ emdb_password }}" 
            status_value: "End of Life"  
            status_reason_value: "Obsolete"                                 
          delegate_to: localhost
          register: output
          until: '"Exception" not in output.cmdb_result or "Error" not in output.cmdb_result' 
          retries: 3
          delay: 30

        - name: Get timestamp from the system
          shell: "date +%Y-%m-%d/%H:%M"
          delegate_to: localhost
          register: tstamp              
                  
        - set_fact:
            time: "{{tstamp.stdout}}"

        - name: "Write Failure host to file"
          shell: echo "{{ inventory_hostname }} Failure" >> phy_cmdb_update_failure.txt                  
          delegate_to: localhost
          when: '"SUCCESSFULLY" not in output.cmdb_result or output is not defined'

        - name: "Failure information to file in rescue block"
          shell: echo "{{ inventory_hostname }}, {{ time }}, [ERROR], {{ output.cmdb_result }} " >> {{file_cmdb_fail}}                    
          delegate_to: localhost
          when: '"SUCCESSFULLY" not in output.cmdb_result or output is not defined'

        - meta: end_host
          when: '"SUCCESSFULLY" not in output.cmdb_result or output is not defined'          

        - name: "Test custom module fetch CMDB with CI status after updating"
          cmdb_fetch_after_update:
            conn_str: "{{ private_endpoint_connection_string }}"
            server_name: '{{cmdb_vmname_new}}'
            cmdb_server: "{{ cmdb_url_update }}" 
            instance_id: '{{ instanceid }}'
            user_name: "{{ emdb_username }}"
            pass_word: "{{ emdb_password }}" 
          delegate_to: localhost
          register: outputcmdb
          until: '"Exception" not in outputcmdb.cmdb_result_after or "Failed" not in outputcmdb.cmdb_result_after' 
          retries: 3
          delay: 20           
          when: '"SUCCESSFULLY" in output.cmdb_result'

        - set_fact:
            cmdb_result_fetch: "{{outputcmdb.cmdb_result_after}}" 

        - name: "Write Failure host to file"
          shell: echo "{{ inventory_hostname }} Failure" >> phy_cmdb_update_failure.txt                  
          delegate_to: localhost
          when: '"SUCCESSFULLY" not in cmdb_result_fetch'  


        - name: "Failure information to File"
          shell: echo "{{ inventory_hostname }}, {{ time }}, [ERROR],Exception occured in CMDB update module kindly check.Either connection issue or server not found" >> {{file_cmdb_fail}}                    
          delegate_to: localhost
          when: '"SUCCESSFULLY" not in cmdb_result_fetch'  

        - meta: end_host
          when: '"Failed to" in cmdb_result_fetch'   

        - name: "success information to file"
          shell: echo "{{ inventory_hostname }}, {{ time }}, [INFO],{{cmdb_result_fetch}}" >> {{file_cmdb_suc}}                    
          delegate_to: localhost
          when: '"SUCCESSFULLY" in cmdb_result_fetch'

        - name: Display the JSON file content
          shell: cat private_endpoint_connection_string.yml
          delegate_to: localhost
          register: result_private_endpoint_connection_string
    
        - name: save the Json data to a Variable as a Fact
          set_fact:
            private_endpoint_connection_string: "{{ result_private_endpoint_connection_string.stdout }}"
          delegate_to: localhost

        - name: "update entry for DECO server for cmdb duplicate check"
          azure_update_module_vals_phy:
            connection_string: "{{ private_endpoint_connection_string }}"
            hostname: "{{inventory_hostname}}"
            module_name: "cmdb_update"
            status: "T"            
          register: update_status
          delegate_to: localhost  
          when: '"SUCCESSFULLY" in cmdb_result_fetch'

                    
        - name: "Check entry for DECO server for filter hostlist for storage cleanup for physical servers"
          azure_update_ref_phy:
            connection_string: "{{ private_endpoint_connection_string }}"
            hostname: "{{inventory_hostname}}"
          register: idem_status 
          delegate_to: localhost
         
        - set_fact: 
            san_cleanup: '{{idem_status.module_update.san_cleanup}}' 
            
        - set_fact: 
            cmdb_update: '{{idem_status.module_update.cmdb_update}}' 

        - name: Get timestamp from the system
          shell: "date +%Y-%m-%d"
          delegate_to: localhost
          register: tstamp              
                  
        - set_fact:
            time: "{{tstamp.stdout}}" 

        - name: "update entry for DECO server for Closure date"
          azure_update_module_vals_phy:
            connection_string: "{{ private_endpoint_connection_string }}"
            hostname: "{{inventory_hostname}}"
            module_name: "deco_date"
            status: "{{ time }}"           
          register: update_status_info_date
          delegate_to: localhost  
          when: san_cleanup == "T" and cmdb_update == "T"

        - debug:
            var: "{{ update_status_info_date }}"            
            
      rescue: 
        - name: when above one throws error the below task should execute
          debug:
            msg: "Exception occurred but rescued - check errors for Update_CMDB module" 
          #ignore_errors: yes      

        - set_fact:
            cmdb_result: "{{ output.cmdb_result }}, check errors for CMDB UPDATE module"
##################################################################
        - name: Get timestamp from the system
          shell: "date +%Y-%m-%d/%H:%M"
          delegate_to: localhost
          register: tstamp              
                  
        - set_fact:
            time: "{{tstamp.stdout}}"

        - name: "Write Failure host to file"
          shell: echo "{{ inventory_hostname }} Failure" >> phy_cmdb_update_failure.txt                  
          delegate_to: localhost

        - name: "Failure information to file in rescue block"
          shell: echo "{{ inventory_hostname }}, {{ time }}, [ERROR], {{ cmdb_result }}" >> {{file_cmdb_fail}}                    
          delegate_to: localhost