--- 
    - name: Handle the error
      throttle: 1
      block:       
        - set_fact:
            file_failure_stat: "esxi_stat_failure.yml"
            file_suc_esxi_stat: "esxi_stat_success.yml"


        # - name: Display the JSON file content
        #   shell: cat record_esxi_filter.json
        #   delegate_to: localhost
        #   register: TR_result_esxi_filter

        # - name: save the Json data to a Variable as a Fact
        #   set_fact:
        #     record_id_esxi_filter: "{{ TR_result_esxi_filter.stdout[1:-1] }}"
        #   delegate_to: localhost         

        # - meta: end_host
        #   when: TR_result_esxi_filter == ""             
          
        - name: "Get vendor Type"
          esxi_vendor_fetch:
            esxiname: '{{ inventory_hostname }}'
            synergon_api: '{{synergon_url}}' #"{{ cmdb_url_update }}"
          delegate_to: localhost
          register: output

        - debug:
            var: output

        - set_fact:
            esxi_vendor: "{{output.vendor}}"

        - meta: end_host
          when: esxi_vendor is not defined

        -name: Check any VMs running on host
         fetch_fqdn_vcenter_vmlist_esxi:
           esxiname: '{{ inventory_hostname }}'
           synergon_api: "{{ synergon_url }}"
          delegate_to: localhost
          register: vm_check
          when: esxi_vendor is defined

        - debug:
            var: vm_check
          when: esxi_vendor is defined

        - set_fact:
            vm_info: "{{ vm_check.msg }}"
          when: esxi_vendor is defined
        
        - name: "Get blade/rack Type"
          esxi_type_fetch:
            product: '{{ esxi_vendor }}'
          delegate_to: localhost
          register: output
          when: vm_info is search("no running VMs")

        - debug:
            var: output
          when: vm_info is search("no running VMs")
 
        - meta: end_host
          when: vm_info is not search("no running VMs")

        - name: Get timestamp from the system
          shell: "date +%Y-%m-%d/%H:%M"
          delegate_to: localhost
          register: tstamp  
                  
        - set_fact:
            time: "{{tstamp.stdout}}"

        - name: "collecting success info to success file"
          shell: echo "{{ inventory_hostname }}, {{ time }}, [INFO], Successfully fetched server information and updated the type {{ output.blade_servers }}" >> {{file_suc_esxi_stat}}                   
          delegate_to: localhost 
          when: output is defined

        - name: "collecting Failure info to Failure file"
          shell: echo "{{ inventory_hostname }}, {{ time }}, [ERROR], Unable to fetch the server info" >> {{file_failure_stat}}                   
          delegate_to: localhost 
          when: output is not defined
 
      rescue:
        - name: when above one throws error the below task should execute
          debug:
             msg: "Exception occurred but rescued - check errors for ESXI Filter Module"

                  

##################################################################################
        - name: Get timestamp from the system
          shell: "date +%Y-%m-%d/%H:%M"
          delegate_to: localhost
          register: tstamp  
                  
        - set_fact:
            time: "{{tstamp.stdout}}"  

        - name: "esxi failure host list"
          shell: echo "{{ inventory_hostname }}, {{ time }}, [ERROR], fetch Fetch ESXI host type failed with errors " >> {{file_failure_stat}}                    
          delegate_to: localhost  