---
    - name: "CMDB Health check status"
      block:

        # - name: Display CMDB URL JSON file content
        #   shell: cat cmdb_url_update.yml
        #   delegate_to: localhost
        #   register: result_cmdb_url_update

        # - name: save the Json data to a Variable as a Fact
        #   set_fact:
        #     cmdb_url_update: "{{ result_cmdb_url_update.stdout }}" 
        #   delegate_to: localhost      

        - name: Display the JSON file content for cmdb duplicate
          shell: cat record_healthcheck_enclosure.json
          delegate_to: localhost
          register: TR_result_healthcheck

        - name: Save the JSON data to a variable as a fact for CMDB duplicates check
          set_fact:
            record_id_cmdb_dup: "{{ TR_result_healthcheck.stdout[1:-1] }}"
          delegate_to: localhost         

        - name: End host if no CMDB records are found
          meta: end_host
          when: record_id_cmdb_dup == ""

        - name: Check if remedy api up or not
          uri:
            url: "{{ cmdb_url_update }}/api/arsys/v1/entry" # http://{{ cmdb_url_update }}:8008/api/arsys/v1/entry
          register: result_remedy
          until: "result_remedy.status == 200"
          retries: 3
          delay: 10

        - name: Get timestamp from the system
          shell: "date +%Y-%m-%d/%H:%M"
          delegate_to: localhost
          register: tstamp
          
                      
        - set_fact:
            time: "{{tstamp.stdout}}"
          

        - name: "Remedy status"
          shell: echo "#Remedy - {{ time }}, [INFO], {{ cmdb_url_update }} is up and running, good to proceed with ESXi deco " >> check_remedy_success.yml   
          delegate_to: localhost
          


      rescue:
        - debug:
            msg: "Remedy is unavaiable to update CMDB"

        - name: Get timestamp from the system
          shell: "date +%Y-%m-%d/%H:%M"
          delegate_to: localhost
          register: tstamp
                      
        - set_fact:
            time: "{{tstamp.stdout}}"
          

        - name: "Remedy status"
          shell: echo "!Remedy - {{ time }}, [ERROR], {{ cmdb_url_update }} is down currently after 3 retries needs attention" >> check_remedy_fail.yml   
          delegate_to: localhost
          
