---
- hosts: localhost
  gather_facts: no
  vars:
    graceperiod_flag: "{{ graceperiod_flag }}"   

  tasks:
  - name: set env for deco
    set_fact:
      env_name: prod

- import_playbook: "phy_{{ graceperiod_flag | lower }}.yml"
  vars:
    env: "{{ env_name }}"