---
    - name: handle the error before grace period vcenter search for vm
      throttle: 1 
      block: 

        - name: Display the JSON file content
          shell: cat private_endpoint_connection_string.yml
          delegate_to: localhost
          register: result_private_endpoint_connection_string
    
        - name: save the Json data to a Variable as a Fact
          set_fact:
            private_endpoint_connection_string: "{{ result_private_endpoint_connection_string.stdout }}"
          delegate_to: localhost

        - name: "Check entry for DECO server"
          azure_update_ref:
            connection_string: "{{ private_endpoint_connection_string }}"
            hostname: "{{inventory_hostname}}"
          register: idem_status
          delegate_to: localhost 

        - set_fact: 
            state_os: '{{idem_status.module_update.os}}'            
                            

        - set_fact:
            opesys: ""

        - name: "Test custom module fetch vcenter details after grace period"
          fetch_vcenter_check:
            vmname: "{{ inventory_hostname }}"     
            synergon_api: '{{ synergon_url }}'
          delegate_to: localhost
          register: vcenter_output_gp
          until: '"Successfully" in vcenter_output_gp.msg or "Unable to find" in vcenter_output_gp.msg or "duplicate entries" in vcenter_output_gp.msg'
          retries: 3
          delay: 30 

        - set_fact:
            v_center_gp_before: "{{vcenter_output_gp.vcenter}}" 
            v_center_msg_gp: "{{vcenter_output_gp.msg}}"

        - set_fact:
            fqdn_vc: ""                

        - set_fact:
            fqdn_vc: .muc.msp.net
          when: v_center_gp_before is not search("mucvcdts02|mucvcdts01|fracol1vcsa1|mucvcsacb01|MUCAMNAZ1|MUCAMNVCPA1|MUCAMNVCPA2|MUCAMNAZ2|MUCAMNVCPB1|MUCAMNVCPB2|MUCAMNAZ3|MUCAMNVCPC1|MUCAMNVCPC2") and v_center_gp_before is not search(".muc.msp.net")

        - set_fact:
            fqdn_vc: .vclassic.net
          when: v_center_gp_before is search("mucvcdts02|mucvcdts01|fracol1vcsa1|mucvcsacb01|MUCAMNAZ1|MUCAMNVCPA1|MUCAMNVCPA2|MUCAMNAZ2|MUCAMNVCPB1|MUCAMNVCPB2|MUCAMNAZ3|MUCAMNVCPC1|MUCAMNVCPC2") and v_center_gp_before is not search(".vclassic.net")                 

        - set_fact:
            v_center: "{{ v_center_gp_before ~ fqdn_vc }}" 

        - set_fact:
            opesys: "{{vcenter_output_gp.opesys}}"     

        - debug: 
            var: v_center   

        - debug: 
            var: opesys

        - name: "update entry for DECO server"
          azure_update_module_vals:
            connection_string: "{{ private_endpoint_connection_string }}"
            hostname: "{{inventory_hostname}}"
            module_name: "os"
            status: "linux"           
          register: update_status
          delegate_to: localhost
          when: opesys is search("Linux|CentOS") and state_os == "F"

        - name: "update entry for DECO server"
          azure_update_module_vals:
            connection_string: "{{ private_endpoint_connection_string }}"
            hostname: "{{inventory_hostname}}"
            module_name: "os"
            status: "windows"            
          register: update_status
          delegate_to: localhost
          when: opesys is search("Windows") and state_os == "F" 

        - name: "update entry for DECO server"
          azure_update_module_vals:
            connection_string: "{{ private_endpoint_connection_string }}"
            hostname: "{{inventory_hostname}}"
            module_name: "os_fetch_status"
            status: "T"           
          register: update_status
          delegate_to: localhost
          when: opesys is search("Linux|CentOS|Windows") and state_os == "F"                                                                           


      rescue: 
        - name: Direct poweroff vcenter fetch
          debug:
            msg: "Exception occurred but rescued - check errors for vcentre_details module in before grace period in direct poweroff vcenter fetch"


    - name: Handle vm status
      throttle: 1
      block:

        - name: Display the JSON file content
          shell: cat private_endpoint_connection_string.yml
          delegate_to: localhost
          register: result_private_endpoint_connection_string
    
        - name: save the Json data to a Variable as a Fact
          set_fact:
            private_endpoint_connection_string: "{{ result_private_endpoint_connection_string.stdout }}"
          delegate_to: localhost

        - name: "Check entry for DECO server"
          azure_update_ref:
            connection_string: "{{ private_endpoint_connection_string }}"
            hostname: "{{inventory_hostname}}"
          register: idem_status
          delegate_to: localhost 

        - set_fact: 
            state_os: '{{idem_status.module_update.os}}'       

        - set_fact:
            os: ""


        - name: awx creds username to var
          set_fact:
            pAccount_user: "{{ paccount_username }}"
          delegate_to: localhost

        - name: awx creds password to var
          set_fact:
            paccount_password: "{{ paccount_password }}"
          delegate_to: localhost


        - name: "Gather VM detailed information associated with the given VM"
          vmware_guest_info:
            hostname: '{{ v_center }}'          
            username: "{{ pAccount_user }}"
            password: "{{ paccount_password }}"
            name: "{{ inventory_hostname }}"      
            validate_certs: no
            datacenter: ""
          delegate_to: localhost            
          register: vmfacts     
            
        - set_fact:
            vir_status: "{{ vmfacts.instance.hw_power_status | lower }}" 

        - debug:
            var: vir_status           

        - name: "update entry for DECO server"
          azure_update_module_vals:
            connection_string: "{{ private_endpoint_connection_string }}"
            hostname: "{{inventory_hostname}}"
            module_name: "nas_validate"
            status: "manual"         
          register: update_status
          delegate_to: localhost
          when: vir_status == "poweredoff" or opesys is search("Red Hat Enterprise Linux 6")

      
        - set_fact:
            os: "{{ vmfacts.instance.hw_guest_full_name }}"
          when: state_os == "F"

        - name: "update entry for DECO server"
          azure_update_module_vals:
            connection_string: "{{ private_endpoint_connection_string }}"
            hostname: "{{inventory_hostname}}"
            module_name: "os"
            status: "linux"          
          register: update_status
          delegate_to: localhost
          when: opesys == "" and opesys is defined and os is search("Linux|CentOS") and state_os is not search("linux") 

        - name: "update entry for DECO server"
          azure_update_module_vals:
            connection_string: "{{ private_endpoint_connection_string }}"
            hostname: "{{inventory_hostname}}"
            module_name: "os"
            status: "windows"          
          register: update_status
          delegate_to: localhost
          when: opesys == "" and opesys is defined and os is search("Windows") and state_os is not search("windows")  

        - name: "update entry for DECO server"
          azure_update_module_vals:
            connection_string: "{{ private_endpoint_connection_string }}"
            hostname: "{{inventory_hostname}}"
            module_name: "os_fetch_status"
            status: "T"            
          register: update_status
          delegate_to: localhost
          when: os is search("Linux|CentOS|Windows") and state_os == "F"                      



        - name: "VM host list"
          shell: echo "#VM :{{ inventory_hostname }} is powered-off hence NAS validation steps will be skipped and taken it for manual intervention" >> qualified_vm.yml                     
          delegate_to: localhost
          when: vir_status == "poweredoff"

        - name: "VM host list"
          shell: echo "#VM :{{ inventory_hostname }} is Red Hat Enterprise Linux 6 hence NAS validation steps will be skipped and taken it for manual intervention" >> qualified_vm.yml                     
          delegate_to: localhost
          when: opesys is search("Red Hat Enterprise Linux 6")               
          
 
      rescue: 
        - name: Direct poweroff vcenter fetch
          debug:
             msg: "Exception occurred but rescued - check errors for direct poweroff vcenter fetch"

